/* Generated by Amaranth Yosys 0.50 (PyPI ver 0.50.0.0.post124, git sha1 b5170e139) */

(* top =  1  *)
(* src = "/home/yym/workspace/fpga/./main.py:35" *)
(* generator = "Amaranth" *)
module top(rst, vauxp1, vauxn1, auto_button, sample_period_control_knob_A, sample_period_control_knob_B, display_gain_control_knob_A, display_gain_control_knob_B, vga_hsync, vga_vsync, vga_r, vga_g, vga_b, clk);
  wire \$1 ;
  (* src = "/home/yym/workspace/fpga/XADCModule.py:10" *)
  wire adc_ready;
  (* src = "/home/yym/workspace/fpga/XADCModule.py:9" *)
  wire [11:0] adc_value;
  (* src = "/home/yym/workspace/fpga/./main.py:26" *)
  input auto_button;
  wire auto_button;
  (* src = "/home/yym/workspace/fpga/./main.py:54" *)
  input clk;
  wire clk;
  (* src = "/home/yym/workspace/fpga/./main.py:54" *)
  wire \clk$17 ;
  (* src = "/home/yym/workspace/fpga/./main.py:39" *)
  wire clk_25m;
  (* src = "/home/yym/workspace/fpga/./main.py:31" *)
  input display_gain_control_knob_A;
  wire display_gain_control_knob_A;
  (* src = "/home/yym/workspace/fpga/./main.py:32" *)
  input display_gain_control_knob_B;
  wire display_gain_control_knob_B;
  (* src = "/home/yym/workspace/fpga/PeriodDetector.py:10" *)
  wire get_period_over;
  (* src = "/home/yym/workspace/fpga/ButtonControl.py:6" *)
  wire out;
  (* src = "/home/yym/workspace/fpga/KnobControl.py:7" *)
  wire [1:0] \out$24 ;
  (* src = "/home/yym/workspace/fpga/KnobControl.py:7" *)
  wire [1:0] \out$32 ;
  (* src = "/home/yym/workspace/fpga/PeriodDetector.py:9" *)
  wire [31:0] period;
  (* src = "/home/yym/workspace/fpga/./main.py:48" *)
  wire pix_clk;
  (* src = "/home/yym/workspace/fpga/./main.py:48" *)
  wire pix_rst;
  (* src = "/home/yym/workspace/fpga/RAM.py:13" *)
  wire [11:0] r_data;
  (* src = "/home/yym/workspace/fpga/./main.py:20" *)
  input rst;
  wire rst;
  (* src = "/home/yym/workspace/fpga/./main.py:54" *)
  wire \rst$18 ;
  (* src = "/home/yym/workspace/fpga/./main.py:28" *)
  input sample_period_control_knob_A;
  wire sample_period_control_knob_A;
  (* src = "/home/yym/workspace/fpga/./main.py:29" *)
  input sample_period_control_knob_B;
  wire sample_period_control_knob_B;
  (* src = "/home/yym/workspace/fpga/./main.py:24" *)
  input vauxn1;
  wire vauxn1;
  (* src = "/home/yym/workspace/fpga/./main.py:23" *)
  input vauxp1;
  wire vauxp1;
  (* src = "/home/yym/workspace/fpga/./main.py:19" *)
  output [3:0] vga_b;
  wire [3:0] vga_b;
  (* src = "/home/yym/workspace/fpga/./main.py:18" *)
  output [3:0] vga_g;
  wire [3:0] vga_g;
  (* src = "/home/yym/workspace/fpga/./main.py:14" *)
  output vga_hsync;
  wire vga_hsync;
  (* src = "/home/yym/workspace/fpga/./main.py:17" *)
  output [3:0] vga_r;
  wire [3:0] vga_r;
  (* src = "/home/yym/workspace/fpga/./main.py:15" *)
  output vga_vsync;
  wire vga_vsync;
  (* src = "/home/yym/workspace/fpga/VGATiming.py:32" *)
  wire visible;
  (* src = "/home/yym/workspace/fpga/WaveControl.py:11" *)
  wire [11:0] w_addr;
  (* src = "/home/yym/workspace/fpga/WaveControl.py:12" *)
  wire [11:0] w_data;
  (* src = "/home/yym/workspace/fpga/WaveControl.py:10" *)
  wire w_en;
  (* src = "/home/yym/workspace/fpga/VGATiming.py:34" *)
  wire [9:0] x;
  (* src = "/home/yym/workspace/fpga/VGATiming.py:35" *)
  wire [9:0] y;
  assign pix_rst = ~ (* src = "/home/yym/workspace/fpga/./main.py:51" *) rst;
  assign \rst$18  = ~ (* src = "/home/yym/workspace/fpga/./main.py:57" *) rst;
  assign \$1  = ~ (* src = "/home/yym/workspace/fpga/./main.py:44" *) rst;
  (* src = "/home/yym/workspace/fpga/./main.py:68" *)
  \top.auto_button$36  \auto_button$36  (
    .auto_button(auto_button),
    .clk(clk),
    .out(out),
    .rst(\rst$18 )
  );
  (* src = "/home/yym/workspace/fpga/./main.py:41" *)
  dcm_25m dcm_25m (
    .clk_in1(clk),
    .clk_out1(pix_clk),
    .reset(\$1 )
  );
  (* src = "/home/yym/workspace/fpga/./main.py:91" *)
  \top.display_gain_control_knob  display_gain_control_knob (
    .clk(clk),
    .display_gain_control_knob_A(display_gain_control_knob_A),
    .display_gain_control_knob_B(display_gain_control_knob_B),
    .out(\out$32 ),
    .rst(\rst$18 )
  );
  (* src = "/home/yym/workspace/fpga/./main.py:73" *)
  \top.period_detector  period_detector (
    .adc_ready(adc_ready),
    .adc_value(adc_value),
    .clk(clk),
    .get_period_over(get_period_over),
    .out(out),
    .period(period),
    .rst(\rst$18 )
  );
  (* src = "/home/yym/workspace/fpga/./main.py:87" *)
  \top.ram  ram (
    .clk(clk),
    .pix_clk(pix_clk),
    .pix_rst(pix_rst),
    .r_data(r_data),
    .rd__addr(x),
    .rst(\rst$18 ),
    .w_addr(w_addr),
    .wr__data(w_data),
    .wr__en(w_en)
  );
  (* src = "/home/yym/workspace/fpga/./main.py:77" *)
  \top.sample_period_control_knob  sample_period_control_knob (
    .clk(clk),
    .out(\out$24 ),
    .rst(\rst$18 ),
    .sample_period_control_knob_A(sample_period_control_knob_A),
    .sample_period_control_knob_B(sample_period_control_knob_B)
  );
  (* src = "/home/yym/workspace/fpga/./main.py:62" *)
  \top.timing  timing (
    .h_cnt(x),
    .hsync(vga_hsync),
    .pix_clk(pix_clk),
    .pix_rst(pix_rst),
    .v_cnt(y),
    .visible(visible),
    .vsync(vga_vsync)
  );
  (* src = "/home/yym/workspace/fpga/./main.py:97" *)
  \top.vga_display  vga_display (
    .b(vga_b),
    .clk(clk),
    .g(vga_g),
    .out(\out$32 ),
    .pix_clk(pix_clk),
    .pix_rst(pix_rst),
    .r(vga_r),
    .r_data(r_data),
    .rst(\rst$18 ),
    .visible(visible),
    .x(x),
    .y(y)
  );
  (* src = "/home/yym/workspace/fpga/./main.py:83" *)
  \top.wave_control  wave_control (
    .adc_ready(adc_ready),
    .adc_value(adc_value),
    .clk(clk),
    .get_period_over(get_period_over),
    .out(\out$24 ),
    .period(period),
    .rst(\rst$18 ),
    .w_addr(w_addr),
    .w_data(w_data),
    .w_en(w_en)
  );
  (* src = "/home/yym/workspace/fpga/./main.py:65" *)
  \top.xadc  xadc (
    .adc_ready(adc_ready),
    .adc_value(adc_value),
    .clk(clk),
    .rst(\rst$18 ),
    .vauxn1(vauxn1),
    .vauxp1(vauxp1)
  );
  assign clk_25m = pix_clk;
  assign \clk$17  = clk;
endmodule

(* src = "/home/yym/workspace/fpga/ButtonControl.py:9" *)
(* generator = "Amaranth" *)
module \top.auto_button$36 (auto_button, rst, out, clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$1  = 0;
  wire \$1 ;
  reg \$10 ;
  reg [31:0] \$11 ;
  reg \$12 ;
  reg \$13 ;
  wire [32:0] \$2 ;
  wire \$3 ;
  wire \$4 ;
  wire [32:0] \$5 ;
  wire \$6 ;
  wire \$7 ;
  wire \$8 ;
  reg \$9 ;
  (* src = "/home/yym/workspace/fpga/./main.py:26" *)
  input auto_button;
  wire auto_button;
  (* src = "/home/yym/workspace/fpga/./main.py:54" *)
  input clk;
  wire clk;
  (* src = "/home/yym/workspace/fpga/ButtonControl.py:13" *)
  reg [31:0] cnt = 32'd0;
  (* src = "/home/yym/miniconda3/envs/amaranth/lib/python3.12/contextlib.py:144" *)
  reg fsm_state = 1'h0;
  (* src = "/home/yym/workspace/fpga/ButtonControl.py:12" *)
  reg last_status = 1'h0;
  (* src = "/home/yym/workspace/fpga/ButtonControl.py:6" *)
  output out;
  reg out = 1'h0;
  (* src = "/home/yym/workspace/fpga/./main.py:54" *)
  input rst;
  wire rst;
  (* src = "/home/yym/workspace/fpga/ButtonControl.py:11" *)
  reg status = 1'h0;
  assign \$2  = cnt + (* src = "/home/yym/workspace/fpga/ButtonControl.py:22" *) 1'h1;
  assign \$3  = cnt >= (* src = "/home/yym/workspace/fpga/ButtonControl.py:25" *) 20'hf4240;
  assign \$4  = ! (* src = "/home/yym/workspace/fpga/ButtonControl.py:33" *) status;
  assign \$5  = cnt + (* src = "/home/yym/workspace/fpga/ButtonControl.py:34" *) 1'h1;
  assign \$6  = cnt >= (* src = "/home/yym/workspace/fpga/ButtonControl.py:37" *) 20'hf4240;
  assign \$7  = ! (* src = "/home/yym/miniconda3/envs/amaranth/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) fsm_state;
  (* src = "/home/yym/workspace/fpga/ButtonControl.py:12" *)
  always @(posedge clk)
    last_status <= \$9 ;
  (* src = "/home/yym/workspace/fpga/ButtonControl.py:11" *)
  always @(posedge clk)
    status <= \$10 ;
  (* src = "/home/yym/workspace/fpga/ButtonControl.py:13" *)
  always @(posedge clk)
    cnt <= \$11 ;
  (* src = "/home/yym/workspace/fpga/ButtonControl.py:6" *)
  always @(posedge clk)
    out <= \$12 ;
  (* src = "/home/yym/miniconda3/envs/amaranth/lib/python3.12/contextlib.py:144" *)
  always @(posedge clk)
    fsm_state <= \$13 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$9  = status;
    if (rst) begin
      \$9  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$10  = auto_button;
    if (rst) begin
      \$10  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    casez (fsm_state)
      1'h0:
        begin
          (* full_case = 32'd1 *)
          if (\$1 ) begin
            \$11  = \$2 [31:0];
          end else begin
            \$11  = 32'd0;
          end
          if (\$3 ) begin
            \$11  = 32'd0;
          end
        end
      1'h1:
        begin
          (* full_case = 32'd1 *)
          if (\$4 ) begin
            \$11  = \$5 [31:0];
          end else begin
            \$11  = 32'd0;
          end
          if (\$6 ) begin
            \$11  = 32'd0;
          end
        end
    endcase
    if (rst) begin
      \$11  = 32'd0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$12  = out;
    (* full_case = 32'd1 *)
    casez (fsm_state)
      1'h0:
          if (\$3 ) begin
            \$12  = 1'h1;
          end
      1'h1:
          \$12  = 1'h0;
    endcase
    if (rst) begin
      \$12  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$13  = fsm_state;
    (* full_case = 32'd1 *)
    casez (fsm_state)
      1'h0:
          if (\$3 ) begin
            \$13  = 1'h1;
          end
      1'h1:
          if (\$6 ) begin
            \$13  = 1'h0;
          end
    endcase
    if (rst) begin
      \$13  = 1'h0;
    end
  end
  assign \$1  = status;
  assign \$8  = fsm_state;
endmodule

(* src = "/home/yym/workspace/fpga/KnobControl.py:10" *)
(* generator = "Amaranth" *)
module \top.display_gain_control_knob (display_gain_control_knob_A, display_gain_control_knob_B, rst, out, clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$2  = 0;
  wire [1:0] \$1 ;
  wire \$10 ;
  wire \$11 ;
  wire \$12 ;
  wire \$13 ;
  wire \$14 ;
  wire \$15 ;
  wire \$16 ;
  wire \$17 ;
  reg [1:0] \$18 ;
  reg [1:0] \$19 ;
  wire [2:0] \$2 ;
  reg [31:0] \$20 ;
  reg \$21 ;
  reg \$22 ;
  reg [1:0] \$23 ;
  reg [1:0] \$24 ;
  reg [1:0] \$25 ;
  wire \$3 ;
  wire \$4 ;
  wire [32:0] \$5 ;
  wire \$6 ;
  wire \$7 ;
  wire \$8 ;
  wire \$9 ;
  (* src = "/home/yym/workspace/fpga/./main.py:54" *)
  input clk;
  wire clk;
  (* src = "/home/yym/workspace/fpga/KnobControl.py:17" *)
  reg [31:0] cnt = 32'd0;
  (* src = "/home/yym/workspace/fpga/./main.py:31" *)
  input display_gain_control_knob_A;
  wire display_gain_control_knob_A;
  (* src = "/home/yym/workspace/fpga/./main.py:32" *)
  input display_gain_control_knob_B;
  wire display_gain_control_knob_B;
  (* src = "/home/yym/miniconda3/envs/amaranth/lib/python3.12/contextlib.py:144" *)
  reg fsm_state = 1'h1;
  (* src = "/home/yym/workspace/fpga/KnobControl.py:15" *)
  reg [1:0] last_stable_status = 2'h0;
  (* src = "/home/yym/workspace/fpga/KnobControl.py:16" *)
  reg [1:0] last_status = 2'h0;
  (* src = "/home/yym/workspace/fpga/KnobControl.py:7" *)
  output [1:0] out;
  reg [1:0] out = 2'h0;
  (* src = "/home/yym/workspace/fpga/./main.py:54" *)
  input rst;
  wire rst;
  (* src = "/home/yym/workspace/fpga/KnobControl.py:12" *)
  reg stable = 1'h0;
  (* src = "/home/yym/workspace/fpga/KnobControl.py:14" *)
  reg [1:0] stable_status = 2'h0;
  (* src = "/home/yym/workspace/fpga/KnobControl.py:13" *)
  reg [1:0] status = 2'h0;
  assign \$2  = \$1  + (* src = "/home/yym/workspace/fpga/KnobControl.py:20" *) display_gain_control_knob_B;
  assign \$3  = status != (* src = "/home/yym/workspace/fpga/KnobControl.py:25" *) last_status;
  assign \$4  = status == (* src = "/home/yym/workspace/fpga/KnobControl.py:29" *) last_status;
  assign \$5  = cnt + (* src = "/home/yym/workspace/fpga/KnobControl.py:30" *) 1'h1;
  assign \$6  = cnt >= (* src = "/home/yym/workspace/fpga/KnobControl.py:34" *) 20'hf4240;
  assign \$7  = stable_status == (* src = "/home/yym/workspace/fpga/KnobControl.py:44" *) 1'h1;
  assign \$8  = stable_status == (* src = "/home/yym/workspace/fpga/KnobControl.py:46" *) 2'h2;
  assign \$9  = stable_status == (* src = "/home/yym/workspace/fpga/KnobControl.py:49" *) 2'h3;
  assign \$10  = ! (* src = "/home/yym/workspace/fpga/KnobControl.py:51" *) stable_status;
  assign \$11  = stable_status == (* src = "/home/yym/workspace/fpga/KnobControl.py:54" *) 2'h2;
  assign \$12  = stable_status == (* src = "/home/yym/workspace/fpga/KnobControl.py:56" *) 1'h1;
  assign \$13  = ! (* src = "/home/yym/workspace/fpga/KnobControl.py:59" *) stable_status;
  assign \$14  = stable_status == (* src = "/home/yym/workspace/fpga/KnobControl.py:61" *) 2'h3;
  assign \$15  = | (* src = "/home/yym/workspace/fpga/KnobControl.py:68" *) out;
  assign \$16  = ! (* src = "/home/yym/miniconda3/envs/amaranth/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) fsm_state;
  (* src = "/home/yym/workspace/fpga/KnobControl.py:16" *)
  always @(posedge clk)
    last_status <= \$18 ;
  (* src = "/home/yym/workspace/fpga/KnobControl.py:13" *)
  always @(posedge clk)
    status <= \$19 ;
  (* src = "/home/yym/workspace/fpga/KnobControl.py:17" *)
  always @(posedge clk)
    cnt <= \$20 ;
  (* src = "/home/yym/miniconda3/envs/amaranth/lib/python3.12/contextlib.py:144" *)
  always @(posedge clk)
    fsm_state <= \$21 ;
  (* src = "/home/yym/workspace/fpga/KnobControl.py:12" *)
  always @(posedge clk)
    stable <= \$22 ;
  (* src = "/home/yym/workspace/fpga/KnobControl.py:14" *)
  always @(posedge clk)
    stable_status <= \$23 ;
  (* src = "/home/yym/workspace/fpga/KnobControl.py:7" *)
  always @(posedge clk)
    out <= \$24 ;
  (* src = "/home/yym/workspace/fpga/KnobControl.py:15" *)
  always @(posedge clk)
    last_stable_status <= \$25 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$18  = status;
    if (rst) begin
      \$18  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$19  = \$2 [1:0];
    if (rst) begin
      \$19  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$20  = cnt;
    (* full_case = 32'd1 *)
    casez (fsm_state)
      1'h0:
          if (\$3 ) begin
            \$20  = 32'd0;
          end
      1'h1:
          (* full_case = 32'd1 *)
          if (\$4 ) begin
            \$20  = \$5 [31:0];
          end else begin
            \$20  = 32'd0;
          end
    endcase
    if (rst) begin
      \$20  = 32'd0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$21  = fsm_state;
    (* full_case = 32'd1 *)
    casez (fsm_state)
      1'h0:
          if (\$3 ) begin
            \$21  = 1'h1;
          end
      1'h1:
          if (\$6 ) begin
            \$21  = 1'h0;
          end
    endcase
    if (rst) begin
      \$21  = 1'h1;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$22  = stable;
    (* full_case = 32'd1 *)
    casez (fsm_state)
      1'h0:
          /* empty */;
      1'h1:
          if (\$6 ) begin
            \$22  = 1'h1;
          end
    endcase
    if (stable) begin
      \$22  = 1'h0;
    end
    if (rst) begin
      \$22  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$23  = stable_status;
    (* full_case = 32'd1 *)
    casez (fsm_state)
      1'h0:
          /* empty */;
      1'h1:
          if (\$6 ) begin
            \$23  = status;
          end
    endcase
    if (rst) begin
      \$23  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$24  = out;
    if (stable) begin
      (* full_case = 32'd1 *)
      casez (last_stable_status)
        2'h0:
            if (\$7 ) begin
              \$24  = 2'h1;
            end else if (\$8 ) begin
              \$24  = 2'h2;
            end
        2'h1:
            if (\$9 ) begin
              \$24  = 2'h1;
            end else if (\$10 ) begin
              \$24  = 2'h2;
            end
        2'h3:
            if (\$11 ) begin
              \$24  = 2'h1;
            end else if (\$12 ) begin
              \$24  = 2'h2;
            end
        2'h2:
            if (\$13 ) begin
              \$24  = 2'h1;
            end else if (\$14 ) begin
              \$24  = 2'h2;
            end
      endcase
    end
    if (\$15 ) begin
      \$24  = 2'h0;
    end
    if (rst) begin
      \$24  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$25  = last_stable_status;
    if (stable) begin
      \$25  = stable_status;
    end
    if (rst) begin
      \$25  = 2'h0;
    end
  end
  assign \$1  = { display_gain_control_knob_A, 1'h0 };
  assign \$17  = fsm_state;
endmodule

(* src = "/home/yym/workspace/fpga/PeriodDetector.py:12" *)
(* generator = "Amaranth" *)
module \top.period_detector (rst, adc_value, adc_ready, out, period, get_period_over, clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$3  = 0;
  wire [32:0] \$1 ;
  wire [14:0] \$10 ;
  wire [15:0] \$11 ;
  wire [16:0] \$12 ;
  wire [16:0] \$13 ;
  wire [14:0] \$14 ;
  wire [15:0] \$15 ;
  wire [16:0] \$16 ;
  wire [16:0] \$17 ;
  wire \$18 ;
  wire \$19 ;
  wire \$2 ;
  wire \$20 ;
  wire [32:0] \$21 ;
  wire [31:0] \$22 ;
  wire \$23 ;
  wire \$24 ;
  wire \$25 ;
  wire \$26 ;
  wire \$27 ;
  wire \$28 ;
  reg [31:0] \$29 ;
  wire [13:0] \$3 ;
  reg [13:0] \$30 ;
  reg [13:0] \$31 ;
  reg [31:0] \$32 ;
  reg [2:0] \$33 ;
  reg [13:0] \$34 ;
  reg [13:0] \$35 ;
  reg [13:0] \$36 ;
  reg \$37 ;
  reg [31:0] \$38 ;
  reg [31:0] \$39 ;
  wire \$4 ;
  reg \$40 ;
  reg [31:0] \$41 ;
  wire [13:0] \$5 ;
  wire [32:0] \$6 ;
  wire \$7 ;
  wire [14:0] \$8 ;
  wire [14:0] \$9 ;
  (* src = "/home/yym/workspace/fpga/XADCModule.py:10" *)
  input adc_ready;
  wire adc_ready;
  (* src = "/home/yym/workspace/fpga/XADCModule.py:9" *)
  input [11:0] adc_value;
  wire [11:0] adc_value;
  (* src = "/home/yym/workspace/fpga/PeriodDetector.py:8" *)
  reg [31:0] average = 32'd0;
  (* src = "/home/yym/workspace/fpga/./main.py:54" *)
  input clk;
  wire clk;
  (* src = "/home/yym/miniconda3/envs/amaranth/lib/python3.12/contextlib.py:144" *)
  reg [2:0] fsm_state = 3'h0;
  (* src = "/home/yym/workspace/fpga/PeriodDetector.py:10" *)
  output get_period_over;
  reg get_period_over = 1'h0;
  (* src = "/home/yym/workspace/fpga/PeriodDetector.py:24" *)
  reg get_period_ready = 1'h0;
  (* src = "/home/yym/workspace/fpga/PeriodDetector.py:16" *)
  reg [13:0] maxn = 14'h0000;
  (* src = "/home/yym/workspace/fpga/PeriodDetector.py:18" *)
  reg [13:0] mid = 14'h0000;
  (* src = "/home/yym/workspace/fpga/PeriodDetector.py:19" *)
  reg [13:0] mid_high = 14'h0000;
  (* src = "/home/yym/workspace/fpga/PeriodDetector.py:20" *)
  reg [13:0] mid_low = 14'h0000;
  (* src = "/home/yym/workspace/fpga/PeriodDetector.py:17" *)
  reg [13:0] minn = 14'h0fff;
  (* src = "/home/yym/workspace/fpga/ButtonControl.py:6" *)
  input out;
  wire out;
  (* src = "/home/yym/workspace/fpga/PeriodDetector.py:9" *)
  output [31:0] period;
  reg [31:0] period = 32'd1000000;
  (* src = "/home/yym/workspace/fpga/PeriodDetector.py:23" *)
  reg [31:0] period_cnt = 32'd0;
  (* src = "/home/yym/workspace/fpga/PeriodDetector.py:22" *)
  reg [31:0] period_sum = 32'd0;
  (* src = "/home/yym/workspace/fpga/./main.py:54" *)
  input rst;
  wire rst;
  (* src = "/home/yym/workspace/fpga/PeriodDetector.py:21" *)
  reg [31:0] timeout = 32'd0;
  assign \$1  = period_sum + (* src = "/home/yym/workspace/fpga/PeriodDetector.py:27" *) 1'h1;
  assign \$2  = adc_value > (* src = "/home/yym/workspace/fpga/PeriodDetector.py:42" *) maxn;
  assign \$3  = \$2  ? (* src = "/home/yym/workspace/fpga/PeriodDetector.py:42" *) { 2'h0, adc_value } : maxn;
  assign \$4  = adc_value < (* src = "/home/yym/workspace/fpga/PeriodDetector.py:43" *) minn;
  assign \$5  = \$4  ? (* src = "/home/yym/workspace/fpga/PeriodDetector.py:43" *) { 2'h0, adc_value } : minn;
  assign \$6  = timeout + (* src = "/home/yym/workspace/fpga/PeriodDetector.py:45" *) 1'h1;
  assign \$7  = timeout == (* src = "/home/yym/workspace/fpga/PeriodDetector.py:46" *) 27'h5f5e100;
  assign \$8  = maxn + (* src = "/home/yym/workspace/fpga/PeriodDetector.py:48" *) minn;
  assign \$10  = maxn + (* src = "/home/yym/workspace/fpga/PeriodDetector.py:49" *) maxn;
  assign \$11  = \$10  + (* src = "/home/yym/workspace/fpga/PeriodDetector.py:49" *) maxn;
  assign \$12  = \$11  + (* src = "/home/yym/workspace/fpga/PeriodDetector.py:49" *) minn;
  assign \$14  = maxn + (* src = "/home/yym/workspace/fpga/PeriodDetector.py:50" *) minn;
  assign \$15  = \$14  + (* src = "/home/yym/workspace/fpga/PeriodDetector.py:50" *) minn;
  assign \$16  = \$15  + (* src = "/home/yym/workspace/fpga/PeriodDetector.py:50" *) minn;
  assign \$18  = adc_value < (* src = "/home/yym/workspace/fpga/PeriodDetector.py:58" *) mid_low;
  assign \$19  = adc_value > (* src = "/home/yym/workspace/fpga/PeriodDetector.py:63" *) mid;
  assign \$20  = period_cnt <= (* src = "/home/yym/workspace/fpga/PeriodDetector.py:65" *) 4'hf;
  assign \$21  = period_cnt + (* src = "/home/yym/workspace/fpga/PeriodDetector.py:66" *) 1'h1;
  assign \$23  = adc_value > (* src = "/home/yym/workspace/fpga/PeriodDetector.py:80" *) mid_high;
  assign \$24  = ! (* src = "/home/yym/miniconda3/envs/amaranth/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) fsm_state;
  assign \$25  = fsm_state == (* src = "/home/yym/miniconda3/envs/amaranth/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) 1'h1;
  assign \$26  = fsm_state == (* src = "/home/yym/miniconda3/envs/amaranth/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) 2'h2;
  assign \$27  = fsm_state == (* src = "/home/yym/miniconda3/envs/amaranth/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) 2'h3;
  assign \$28  = fsm_state == (* src = "/home/yym/miniconda3/envs/amaranth/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) 3'h4;
  (* src = "/home/yym/workspace/fpga/PeriodDetector.py:22" *)
  always @(posedge clk)
    period_sum <= \$29 ;
  (* src = "/home/yym/workspace/fpga/PeriodDetector.py:16" *)
  always @(posedge clk)
    maxn <= \$30 ;
  (* src = "/home/yym/workspace/fpga/PeriodDetector.py:17" *)
  always @(posedge clk)
    minn <= \$31 ;
  (* src = "/home/yym/workspace/fpga/PeriodDetector.py:21" *)
  always @(posedge clk)
    timeout <= \$32 ;
  (* src = "/home/yym/miniconda3/envs/amaranth/lib/python3.12/contextlib.py:144" *)
  always @(posedge clk)
    fsm_state <= \$33 ;
  (* src = "/home/yym/workspace/fpga/PeriodDetector.py:18" *)
  always @(posedge clk)
    mid <= \$34 ;
  (* src = "/home/yym/workspace/fpga/PeriodDetector.py:19" *)
  always @(posedge clk)
    mid_high <= \$35 ;
  (* src = "/home/yym/workspace/fpga/PeriodDetector.py:20" *)
  always @(posedge clk)
    mid_low <= \$36 ;
  (* src = "/home/yym/workspace/fpga/PeriodDetector.py:24" *)
  always @(posedge clk)
    get_period_ready <= \$37 ;
  (* src = "/home/yym/workspace/fpga/PeriodDetector.py:23" *)
  always @(posedge clk)
    period_cnt <= \$38 ;
  (* src = "/home/yym/workspace/fpga/PeriodDetector.py:9" *)
  always @(posedge clk)
    period <= \$39 ;
  (* src = "/home/yym/workspace/fpga/PeriodDetector.py:10" *)
  always @(posedge clk)
    get_period_over <= \$40 ;
  (* src = "/home/yym/workspace/fpga/PeriodDetector.py:8" *)
  always @(posedge clk)
    average <= \$41 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    \$29  = period_sum;
    if (get_period_ready) begin
      \$29  = \$1 [31:0];
    end
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          if (\$7 ) begin
            \$29  = 32'd0;
          end
    endcase
    if (rst) begin
      \$29  = 32'd0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    \$30  = maxn;
    casez (fsm_state)
      3'h0:
          if (out) begin
            \$30  = 14'h0000;
          end
      3'h1:
          if (adc_ready) begin
            \$30  = \$3 ;
          end
    endcase
    if (rst) begin
      \$30  = 14'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    \$31  = minn;
    casez (fsm_state)
      3'h0:
          if (out) begin
            \$31  = 14'h0fff;
          end
      3'h1:
          if (adc_ready) begin
            \$31  = \$5 ;
          end
    endcase
    if (rst) begin
      \$31  = 14'h0fff;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    \$32  = timeout;
    casez (fsm_state)
      3'h0:
          if (out) begin
            \$32  = 32'd0;
          end
      3'h1:
          \$32  = \$6 [31:0];
    endcase
    if (rst) begin
      \$32  = 32'd0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    \$33  = fsm_state;
    casez (fsm_state)
      3'h0:
          if (out) begin
            \$33  = 3'h1;
          end
      3'h1:
          if (\$7 ) begin
            \$33  = 3'h2;
          end
      3'h2:
          if (adc_ready) begin
            if (\$18 ) begin
              \$33  = 3'h3;
            end
          end
      3'h3:
          if (adc_ready) begin
            if (\$19 ) begin
              (* full_case = 32'd1 *)
              if (\$20 ) begin
                \$33  = 3'h4;
              end else begin
                \$33  = 3'h0;
              end
            end
          end
      3'h4:
          if (adc_ready) begin
            if (\$23 ) begin
              \$33  = 3'h2;
            end
          end
    endcase
    if (rst) begin
      \$33  = 3'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    \$34  = mid;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          if (\$7 ) begin
            \$34  = \$9 [13:0];
          end
    endcase
    if (rst) begin
      \$34  = 14'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    \$35  = mid_high;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          if (\$7 ) begin
            \$35  = \$13 [13:0];
          end
    endcase
    if (rst) begin
      \$35  = 14'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    \$36  = mid_low;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          if (\$7 ) begin
            \$36  = \$17 [13:0];
          end
    endcase
    if (rst) begin
      \$36  = 14'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    \$37  = get_period_ready;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          if (\$7 ) begin
            \$37  = 1'h0;
          end
      3'h2:
          /* empty */;
      3'h3:
          if (adc_ready) begin
            if (\$19 ) begin
              \$37  = 1'h1;
              (* full_case = 32'd1 *)
              if (\$20 ) begin
              end else begin
                \$37  = 1'h0;
              end
            end
          end
    endcase
    if (rst) begin
      \$37  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    \$38  = period_cnt;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          /* empty */;
      3'h2:
          /* empty */;
      3'h3:
          if (adc_ready) begin
            if (\$19 ) begin
              (* full_case = 32'd1 *)
              if (\$20 ) begin
                \$38  = \$21 [31:0];
              end else begin
                \$38  = 32'd0;
              end
            end
          end
    endcase
    if (rst) begin
      \$38  = 32'd0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    \$39  = period;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          /* empty */;
      3'h2:
          /* empty */;
      3'h3:
          if (adc_ready) begin
            if (\$19 ) begin
              (* full_case = 32'd1 *)
              if (\$20 ) begin
              end else begin
                \$39  = \$22 ;
              end
            end
          end
    endcase
    if (rst) begin
      \$39  = 32'd1000000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    \$40  = get_period_over;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          /* empty */;
      3'h2:
          /* empty */;
      3'h3:
          if (adc_ready) begin
            if (\$19 ) begin
              (* full_case = 32'd1 *)
              if (\$20 ) begin
              end else begin
                \$40  = 1'h1;
              end
            end
          end
    endcase
    if (get_period_over) begin
      \$40  = 1'h0;
    end
    if (rst) begin
      \$40  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    \$41  = average;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          /* empty */;
      3'h2:
          /* empty */;
      3'h3:
          if (adc_ready) begin
            if (\$19 ) begin
              (* full_case = 32'd1 *)
              if (\$20 ) begin
              end else begin
                \$41  = { 18'h00000, mid };
              end
            end
          end
    endcase
    if (rst) begin
      \$41  = 32'd0;
    end
  end
  assign \$9  = { 1'h0, \$8 [14:1] };
  assign \$13  = { 2'h0, \$12 [16:2] };
  assign \$17  = { 2'h0, \$16 [16:2] };
  assign \$22  = { 4'h0, period_sum[31:4] };
endmodule

(* src = "/home/yym/workspace/fpga/RAM.py:16" *)
(* generator = "Amaranth" *)
module \top.ram (pix_rst, rst, pix_clk, r_data, rd__addr, w_addr, wr__en, wr__data, clk);
  (* src = "/home/yym/workspace/fpga/./main.py:54" *)
  input clk;
  wire clk;
  (* src = "/home/yym/workspace/fpga/./main.py:48" *)
  input pix_clk;
  wire pix_clk;
  (* src = "/home/yym/workspace/fpga/./main.py:48" *)
  input pix_rst;
  wire pix_rst;
  (* src = "/home/yym/miniconda3/envs/amaranth/lib/python3.12/site-packages/amaranth/lib/memory.py:241" *)
  output [11:0] r_data;
  wire [11:0] r_data;
  (* src = "/home/yym/workspace/fpga/VGATiming.py:34" *)
  input [9:0] rd__addr;
  wire [9:0] rd__addr;
  (* src = "/home/yym/miniconda3/envs/amaranth/lib/python3.12/site-packages/amaranth/lib/memory.py:241" *)
  wire [11:0] rd__data;
  (* src = "/home/yym/miniconda3/envs/amaranth/lib/python3.12/site-packages/amaranth/lib/memory.py:239" *)
  wire rd__en;
  (* src = "/home/yym/workspace/fpga/./main.py:54" *)
  input rst;
  wire rst;
  (* src = "/home/yym/workspace/fpga/WaveControl.py:11" *)
  input [11:0] w_addr;
  wire [11:0] w_addr;
  (* src = "/home/yym/workspace/fpga/WaveControl.py:12" *)
  wire [11:0] w_data;
  (* src = "/home/yym/workspace/fpga/WaveControl.py:10" *)
  wire w_en;
  (* src = "/home/yym/miniconda3/envs/amaranth/lib/python3.12/site-packages/amaranth/lib/memory.py:401" *)
  wire [9:0] wr__addr;
  (* src = "/home/yym/workspace/fpga/WaveControl.py:12" *)
  input [11:0] wr__data;
  wire [11:0] wr__data;
  (* src = "/home/yym/workspace/fpga/WaveControl.py:10" *)
  input wr__en;
  wire wr__en;
  (* src = "/home/yym/workspace/fpga/VGATiming.py:34" *)
  wire [9:0] x;
  (* src = "/home/yym/workspace/fpga/RAM.py:19" *)
  reg [11:0] ram [639:0];
  initial begin
    ram[0] = 12'h000;
    ram[1] = 12'h000;
    ram[2] = 12'h000;
    ram[3] = 12'h000;
    ram[4] = 12'h000;
    ram[5] = 12'h000;
    ram[6] = 12'h000;
    ram[7] = 12'h000;
    ram[8] = 12'h000;
    ram[9] = 12'h000;
    ram[10] = 12'h000;
    ram[11] = 12'h000;
    ram[12] = 12'h000;
    ram[13] = 12'h000;
    ram[14] = 12'h000;
    ram[15] = 12'h000;
    ram[16] = 12'h000;
    ram[17] = 12'h000;
    ram[18] = 12'h000;
    ram[19] = 12'h000;
    ram[20] = 12'h000;
    ram[21] = 12'h000;
    ram[22] = 12'h000;
    ram[23] = 12'h000;
    ram[24] = 12'h000;
    ram[25] = 12'h000;
    ram[26] = 12'h000;
    ram[27] = 12'h000;
    ram[28] = 12'h000;
    ram[29] = 12'h000;
    ram[30] = 12'h000;
    ram[31] = 12'h000;
    ram[32] = 12'h000;
    ram[33] = 12'h000;
    ram[34] = 12'h000;
    ram[35] = 12'h000;
    ram[36] = 12'h000;
    ram[37] = 12'h000;
    ram[38] = 12'h000;
    ram[39] = 12'h000;
    ram[40] = 12'h000;
    ram[41] = 12'h000;
    ram[42] = 12'h000;
    ram[43] = 12'h000;
    ram[44] = 12'h000;
    ram[45] = 12'h000;
    ram[46] = 12'h000;
    ram[47] = 12'h000;
    ram[48] = 12'h000;
    ram[49] = 12'h000;
    ram[50] = 12'h000;
    ram[51] = 12'h000;
    ram[52] = 12'h000;
    ram[53] = 12'h000;
    ram[54] = 12'h000;
    ram[55] = 12'h000;
    ram[56] = 12'h000;
    ram[57] = 12'h000;
    ram[58] = 12'h000;
    ram[59] = 12'h000;
    ram[60] = 12'h000;
    ram[61] = 12'h000;
    ram[62] = 12'h000;
    ram[63] = 12'h000;
    ram[64] = 12'h000;
    ram[65] = 12'h000;
    ram[66] = 12'h000;
    ram[67] = 12'h000;
    ram[68] = 12'h000;
    ram[69] = 12'h000;
    ram[70] = 12'h000;
    ram[71] = 12'h000;
    ram[72] = 12'h000;
    ram[73] = 12'h000;
    ram[74] = 12'h000;
    ram[75] = 12'h000;
    ram[76] = 12'h000;
    ram[77] = 12'h000;
    ram[78] = 12'h000;
    ram[79] = 12'h000;
    ram[80] = 12'h000;
    ram[81] = 12'h000;
    ram[82] = 12'h000;
    ram[83] = 12'h000;
    ram[84] = 12'h000;
    ram[85] = 12'h000;
    ram[86] = 12'h000;
    ram[87] = 12'h000;
    ram[88] = 12'h000;
    ram[89] = 12'h000;
    ram[90] = 12'h000;
    ram[91] = 12'h000;
    ram[92] = 12'h000;
    ram[93] = 12'h000;
    ram[94] = 12'h000;
    ram[95] = 12'h000;
    ram[96] = 12'h000;
    ram[97] = 12'h000;
    ram[98] = 12'h000;
    ram[99] = 12'h000;
    ram[100] = 12'h000;
    ram[101] = 12'h000;
    ram[102] = 12'h000;
    ram[103] = 12'h000;
    ram[104] = 12'h000;
    ram[105] = 12'h000;
    ram[106] = 12'h000;
    ram[107] = 12'h000;
    ram[108] = 12'h000;
    ram[109] = 12'h000;
    ram[110] = 12'h000;
    ram[111] = 12'h000;
    ram[112] = 12'h000;
    ram[113] = 12'h000;
    ram[114] = 12'h000;
    ram[115] = 12'h000;
    ram[116] = 12'h000;
    ram[117] = 12'h000;
    ram[118] = 12'h000;
    ram[119] = 12'h000;
    ram[120] = 12'h000;
    ram[121] = 12'h000;
    ram[122] = 12'h000;
    ram[123] = 12'h000;
    ram[124] = 12'h000;
    ram[125] = 12'h000;
    ram[126] = 12'h000;
    ram[127] = 12'h000;
    ram[128] = 12'h000;
    ram[129] = 12'h000;
    ram[130] = 12'h000;
    ram[131] = 12'h000;
    ram[132] = 12'h000;
    ram[133] = 12'h000;
    ram[134] = 12'h000;
    ram[135] = 12'h000;
    ram[136] = 12'h000;
    ram[137] = 12'h000;
    ram[138] = 12'h000;
    ram[139] = 12'h000;
    ram[140] = 12'h000;
    ram[141] = 12'h000;
    ram[142] = 12'h000;
    ram[143] = 12'h000;
    ram[144] = 12'h000;
    ram[145] = 12'h000;
    ram[146] = 12'h000;
    ram[147] = 12'h000;
    ram[148] = 12'h000;
    ram[149] = 12'h000;
    ram[150] = 12'h000;
    ram[151] = 12'h000;
    ram[152] = 12'h000;
    ram[153] = 12'h000;
    ram[154] = 12'h000;
    ram[155] = 12'h000;
    ram[156] = 12'h000;
    ram[157] = 12'h000;
    ram[158] = 12'h000;
    ram[159] = 12'h000;
    ram[160] = 12'h000;
    ram[161] = 12'h000;
    ram[162] = 12'h000;
    ram[163] = 12'h000;
    ram[164] = 12'h000;
    ram[165] = 12'h000;
    ram[166] = 12'h000;
    ram[167] = 12'h000;
    ram[168] = 12'h000;
    ram[169] = 12'h000;
    ram[170] = 12'h000;
    ram[171] = 12'h000;
    ram[172] = 12'h000;
    ram[173] = 12'h000;
    ram[174] = 12'h000;
    ram[175] = 12'h000;
    ram[176] = 12'h000;
    ram[177] = 12'h000;
    ram[178] = 12'h000;
    ram[179] = 12'h000;
    ram[180] = 12'h000;
    ram[181] = 12'h000;
    ram[182] = 12'h000;
    ram[183] = 12'h000;
    ram[184] = 12'h000;
    ram[185] = 12'h000;
    ram[186] = 12'h000;
    ram[187] = 12'h000;
    ram[188] = 12'h000;
    ram[189] = 12'h000;
    ram[190] = 12'h000;
    ram[191] = 12'h000;
    ram[192] = 12'h000;
    ram[193] = 12'h000;
    ram[194] = 12'h000;
    ram[195] = 12'h000;
    ram[196] = 12'h000;
    ram[197] = 12'h000;
    ram[198] = 12'h000;
    ram[199] = 12'h000;
    ram[200] = 12'h000;
    ram[201] = 12'h000;
    ram[202] = 12'h000;
    ram[203] = 12'h000;
    ram[204] = 12'h000;
    ram[205] = 12'h000;
    ram[206] = 12'h000;
    ram[207] = 12'h000;
    ram[208] = 12'h000;
    ram[209] = 12'h000;
    ram[210] = 12'h000;
    ram[211] = 12'h000;
    ram[212] = 12'h000;
    ram[213] = 12'h000;
    ram[214] = 12'h000;
    ram[215] = 12'h000;
    ram[216] = 12'h000;
    ram[217] = 12'h000;
    ram[218] = 12'h000;
    ram[219] = 12'h000;
    ram[220] = 12'h000;
    ram[221] = 12'h000;
    ram[222] = 12'h000;
    ram[223] = 12'h000;
    ram[224] = 12'h000;
    ram[225] = 12'h000;
    ram[226] = 12'h000;
    ram[227] = 12'h000;
    ram[228] = 12'h000;
    ram[229] = 12'h000;
    ram[230] = 12'h000;
    ram[231] = 12'h000;
    ram[232] = 12'h000;
    ram[233] = 12'h000;
    ram[234] = 12'h000;
    ram[235] = 12'h000;
    ram[236] = 12'h000;
    ram[237] = 12'h000;
    ram[238] = 12'h000;
    ram[239] = 12'h000;
    ram[240] = 12'h000;
    ram[241] = 12'h000;
    ram[242] = 12'h000;
    ram[243] = 12'h000;
    ram[244] = 12'h000;
    ram[245] = 12'h000;
    ram[246] = 12'h000;
    ram[247] = 12'h000;
    ram[248] = 12'h000;
    ram[249] = 12'h000;
    ram[250] = 12'h000;
    ram[251] = 12'h000;
    ram[252] = 12'h000;
    ram[253] = 12'h000;
    ram[254] = 12'h000;
    ram[255] = 12'h000;
    ram[256] = 12'h000;
    ram[257] = 12'h000;
    ram[258] = 12'h000;
    ram[259] = 12'h000;
    ram[260] = 12'h000;
    ram[261] = 12'h000;
    ram[262] = 12'h000;
    ram[263] = 12'h000;
    ram[264] = 12'h000;
    ram[265] = 12'h000;
    ram[266] = 12'h000;
    ram[267] = 12'h000;
    ram[268] = 12'h000;
    ram[269] = 12'h000;
    ram[270] = 12'h000;
    ram[271] = 12'h000;
    ram[272] = 12'h000;
    ram[273] = 12'h000;
    ram[274] = 12'h000;
    ram[275] = 12'h000;
    ram[276] = 12'h000;
    ram[277] = 12'h000;
    ram[278] = 12'h000;
    ram[279] = 12'h000;
    ram[280] = 12'h000;
    ram[281] = 12'h000;
    ram[282] = 12'h000;
    ram[283] = 12'h000;
    ram[284] = 12'h000;
    ram[285] = 12'h000;
    ram[286] = 12'h000;
    ram[287] = 12'h000;
    ram[288] = 12'h000;
    ram[289] = 12'h000;
    ram[290] = 12'h000;
    ram[291] = 12'h000;
    ram[292] = 12'h000;
    ram[293] = 12'h000;
    ram[294] = 12'h000;
    ram[295] = 12'h000;
    ram[296] = 12'h000;
    ram[297] = 12'h000;
    ram[298] = 12'h000;
    ram[299] = 12'h000;
    ram[300] = 12'h000;
    ram[301] = 12'h000;
    ram[302] = 12'h000;
    ram[303] = 12'h000;
    ram[304] = 12'h000;
    ram[305] = 12'h000;
    ram[306] = 12'h000;
    ram[307] = 12'h000;
    ram[308] = 12'h000;
    ram[309] = 12'h000;
    ram[310] = 12'h000;
    ram[311] = 12'h000;
    ram[312] = 12'h000;
    ram[313] = 12'h000;
    ram[314] = 12'h000;
    ram[315] = 12'h000;
    ram[316] = 12'h000;
    ram[317] = 12'h000;
    ram[318] = 12'h000;
    ram[319] = 12'h000;
    ram[320] = 12'h000;
    ram[321] = 12'h000;
    ram[322] = 12'h000;
    ram[323] = 12'h000;
    ram[324] = 12'h000;
    ram[325] = 12'h000;
    ram[326] = 12'h000;
    ram[327] = 12'h000;
    ram[328] = 12'h000;
    ram[329] = 12'h000;
    ram[330] = 12'h000;
    ram[331] = 12'h000;
    ram[332] = 12'h000;
    ram[333] = 12'h000;
    ram[334] = 12'h000;
    ram[335] = 12'h000;
    ram[336] = 12'h000;
    ram[337] = 12'h000;
    ram[338] = 12'h000;
    ram[339] = 12'h000;
    ram[340] = 12'h000;
    ram[341] = 12'h000;
    ram[342] = 12'h000;
    ram[343] = 12'h000;
    ram[344] = 12'h000;
    ram[345] = 12'h000;
    ram[346] = 12'h000;
    ram[347] = 12'h000;
    ram[348] = 12'h000;
    ram[349] = 12'h000;
    ram[350] = 12'h000;
    ram[351] = 12'h000;
    ram[352] = 12'h000;
    ram[353] = 12'h000;
    ram[354] = 12'h000;
    ram[355] = 12'h000;
    ram[356] = 12'h000;
    ram[357] = 12'h000;
    ram[358] = 12'h000;
    ram[359] = 12'h000;
    ram[360] = 12'h000;
    ram[361] = 12'h000;
    ram[362] = 12'h000;
    ram[363] = 12'h000;
    ram[364] = 12'h000;
    ram[365] = 12'h000;
    ram[366] = 12'h000;
    ram[367] = 12'h000;
    ram[368] = 12'h000;
    ram[369] = 12'h000;
    ram[370] = 12'h000;
    ram[371] = 12'h000;
    ram[372] = 12'h000;
    ram[373] = 12'h000;
    ram[374] = 12'h000;
    ram[375] = 12'h000;
    ram[376] = 12'h000;
    ram[377] = 12'h000;
    ram[378] = 12'h000;
    ram[379] = 12'h000;
    ram[380] = 12'h000;
    ram[381] = 12'h000;
    ram[382] = 12'h000;
    ram[383] = 12'h000;
    ram[384] = 12'h000;
    ram[385] = 12'h000;
    ram[386] = 12'h000;
    ram[387] = 12'h000;
    ram[388] = 12'h000;
    ram[389] = 12'h000;
    ram[390] = 12'h000;
    ram[391] = 12'h000;
    ram[392] = 12'h000;
    ram[393] = 12'h000;
    ram[394] = 12'h000;
    ram[395] = 12'h000;
    ram[396] = 12'h000;
    ram[397] = 12'h000;
    ram[398] = 12'h000;
    ram[399] = 12'h000;
    ram[400] = 12'h000;
    ram[401] = 12'h000;
    ram[402] = 12'h000;
    ram[403] = 12'h000;
    ram[404] = 12'h000;
    ram[405] = 12'h000;
    ram[406] = 12'h000;
    ram[407] = 12'h000;
    ram[408] = 12'h000;
    ram[409] = 12'h000;
    ram[410] = 12'h000;
    ram[411] = 12'h000;
    ram[412] = 12'h000;
    ram[413] = 12'h000;
    ram[414] = 12'h000;
    ram[415] = 12'h000;
    ram[416] = 12'h000;
    ram[417] = 12'h000;
    ram[418] = 12'h000;
    ram[419] = 12'h000;
    ram[420] = 12'h000;
    ram[421] = 12'h000;
    ram[422] = 12'h000;
    ram[423] = 12'h000;
    ram[424] = 12'h000;
    ram[425] = 12'h000;
    ram[426] = 12'h000;
    ram[427] = 12'h000;
    ram[428] = 12'h000;
    ram[429] = 12'h000;
    ram[430] = 12'h000;
    ram[431] = 12'h000;
    ram[432] = 12'h000;
    ram[433] = 12'h000;
    ram[434] = 12'h000;
    ram[435] = 12'h000;
    ram[436] = 12'h000;
    ram[437] = 12'h000;
    ram[438] = 12'h000;
    ram[439] = 12'h000;
    ram[440] = 12'h000;
    ram[441] = 12'h000;
    ram[442] = 12'h000;
    ram[443] = 12'h000;
    ram[444] = 12'h000;
    ram[445] = 12'h000;
    ram[446] = 12'h000;
    ram[447] = 12'h000;
    ram[448] = 12'h000;
    ram[449] = 12'h000;
    ram[450] = 12'h000;
    ram[451] = 12'h000;
    ram[452] = 12'h000;
    ram[453] = 12'h000;
    ram[454] = 12'h000;
    ram[455] = 12'h000;
    ram[456] = 12'h000;
    ram[457] = 12'h000;
    ram[458] = 12'h000;
    ram[459] = 12'h000;
    ram[460] = 12'h000;
    ram[461] = 12'h000;
    ram[462] = 12'h000;
    ram[463] = 12'h000;
    ram[464] = 12'h000;
    ram[465] = 12'h000;
    ram[466] = 12'h000;
    ram[467] = 12'h000;
    ram[468] = 12'h000;
    ram[469] = 12'h000;
    ram[470] = 12'h000;
    ram[471] = 12'h000;
    ram[472] = 12'h000;
    ram[473] = 12'h000;
    ram[474] = 12'h000;
    ram[475] = 12'h000;
    ram[476] = 12'h000;
    ram[477] = 12'h000;
    ram[478] = 12'h000;
    ram[479] = 12'h000;
    ram[480] = 12'h000;
    ram[481] = 12'h000;
    ram[482] = 12'h000;
    ram[483] = 12'h000;
    ram[484] = 12'h000;
    ram[485] = 12'h000;
    ram[486] = 12'h000;
    ram[487] = 12'h000;
    ram[488] = 12'h000;
    ram[489] = 12'h000;
    ram[490] = 12'h000;
    ram[491] = 12'h000;
    ram[492] = 12'h000;
    ram[493] = 12'h000;
    ram[494] = 12'h000;
    ram[495] = 12'h000;
    ram[496] = 12'h000;
    ram[497] = 12'h000;
    ram[498] = 12'h000;
    ram[499] = 12'h000;
    ram[500] = 12'h000;
    ram[501] = 12'h000;
    ram[502] = 12'h000;
    ram[503] = 12'h000;
    ram[504] = 12'h000;
    ram[505] = 12'h000;
    ram[506] = 12'h000;
    ram[507] = 12'h000;
    ram[508] = 12'h000;
    ram[509] = 12'h000;
    ram[510] = 12'h000;
    ram[511] = 12'h000;
    ram[512] = 12'h000;
    ram[513] = 12'h000;
    ram[514] = 12'h000;
    ram[515] = 12'h000;
    ram[516] = 12'h000;
    ram[517] = 12'h000;
    ram[518] = 12'h000;
    ram[519] = 12'h000;
    ram[520] = 12'h000;
    ram[521] = 12'h000;
    ram[522] = 12'h000;
    ram[523] = 12'h000;
    ram[524] = 12'h000;
    ram[525] = 12'h000;
    ram[526] = 12'h000;
    ram[527] = 12'h000;
    ram[528] = 12'h000;
    ram[529] = 12'h000;
    ram[530] = 12'h000;
    ram[531] = 12'h000;
    ram[532] = 12'h000;
    ram[533] = 12'h000;
    ram[534] = 12'h000;
    ram[535] = 12'h000;
    ram[536] = 12'h000;
    ram[537] = 12'h000;
    ram[538] = 12'h000;
    ram[539] = 12'h000;
    ram[540] = 12'h000;
    ram[541] = 12'h000;
    ram[542] = 12'h000;
    ram[543] = 12'h000;
    ram[544] = 12'h000;
    ram[545] = 12'h000;
    ram[546] = 12'h000;
    ram[547] = 12'h000;
    ram[548] = 12'h000;
    ram[549] = 12'h000;
    ram[550] = 12'h000;
    ram[551] = 12'h000;
    ram[552] = 12'h000;
    ram[553] = 12'h000;
    ram[554] = 12'h000;
    ram[555] = 12'h000;
    ram[556] = 12'h000;
    ram[557] = 12'h000;
    ram[558] = 12'h000;
    ram[559] = 12'h000;
    ram[560] = 12'h000;
    ram[561] = 12'h000;
    ram[562] = 12'h000;
    ram[563] = 12'h000;
    ram[564] = 12'h000;
    ram[565] = 12'h000;
    ram[566] = 12'h000;
    ram[567] = 12'h000;
    ram[568] = 12'h000;
    ram[569] = 12'h000;
    ram[570] = 12'h000;
    ram[571] = 12'h000;
    ram[572] = 12'h000;
    ram[573] = 12'h000;
    ram[574] = 12'h000;
    ram[575] = 12'h000;
    ram[576] = 12'h000;
    ram[577] = 12'h000;
    ram[578] = 12'h000;
    ram[579] = 12'h000;
    ram[580] = 12'h000;
    ram[581] = 12'h000;
    ram[582] = 12'h000;
    ram[583] = 12'h000;
    ram[584] = 12'h000;
    ram[585] = 12'h000;
    ram[586] = 12'h000;
    ram[587] = 12'h000;
    ram[588] = 12'h000;
    ram[589] = 12'h000;
    ram[590] = 12'h000;
    ram[591] = 12'h000;
    ram[592] = 12'h000;
    ram[593] = 12'h000;
    ram[594] = 12'h000;
    ram[595] = 12'h000;
    ram[596] = 12'h000;
    ram[597] = 12'h000;
    ram[598] = 12'h000;
    ram[599] = 12'h000;
    ram[600] = 12'h000;
    ram[601] = 12'h000;
    ram[602] = 12'h000;
    ram[603] = 12'h000;
    ram[604] = 12'h000;
    ram[605] = 12'h000;
    ram[606] = 12'h000;
    ram[607] = 12'h000;
    ram[608] = 12'h000;
    ram[609] = 12'h000;
    ram[610] = 12'h000;
    ram[611] = 12'h000;
    ram[612] = 12'h000;
    ram[613] = 12'h000;
    ram[614] = 12'h000;
    ram[615] = 12'h000;
    ram[616] = 12'h000;
    ram[617] = 12'h000;
    ram[618] = 12'h000;
    ram[619] = 12'h000;
    ram[620] = 12'h000;
    ram[621] = 12'h000;
    ram[622] = 12'h000;
    ram[623] = 12'h000;
    ram[624] = 12'h000;
    ram[625] = 12'h000;
    ram[626] = 12'h000;
    ram[627] = 12'h000;
    ram[628] = 12'h000;
    ram[629] = 12'h000;
    ram[630] = 12'h000;
    ram[631] = 12'h000;
    ram[632] = 12'h000;
    ram[633] = 12'h000;
    ram[634] = 12'h000;
    ram[635] = 12'h000;
    ram[636] = 12'h000;
    ram[637] = 12'h000;
    ram[638] = 12'h000;
    ram[639] = 12'h000;
  end
  always @(posedge clk) begin
    if (wr__en)
      ram[w_addr[9:0]] <= wr__data;
  end
  reg [11:0] _0_;
  always @(posedge pix_clk) begin
    _0_ <= ram[rd__addr];
  end
  assign r_data = _0_;
  assign w_en = wr__en;
  assign wr__addr = w_addr[9:0];
  assign w_data = wr__data;
  assign rd__en = 1'h1;
  assign x = rd__addr;
  assign rd__data = r_data;
endmodule

(* src = "/home/yym/workspace/fpga/KnobControl.py:10" *)
(* generator = "Amaranth" *)
module \top.sample_period_control_knob (sample_period_control_knob_A, sample_period_control_knob_B, rst, out, clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$4  = 0;
  wire [1:0] \$1 ;
  wire \$10 ;
  wire \$11 ;
  wire \$12 ;
  wire \$13 ;
  wire \$14 ;
  wire \$15 ;
  wire \$16 ;
  wire \$17 ;
  reg [1:0] \$18 ;
  reg [1:0] \$19 ;
  wire [2:0] \$2 ;
  reg [31:0] \$20 ;
  reg \$21 ;
  reg \$22 ;
  reg [1:0] \$23 ;
  reg [1:0] \$24 ;
  reg [1:0] \$25 ;
  wire \$3 ;
  wire \$4 ;
  wire [32:0] \$5 ;
  wire \$6 ;
  wire \$7 ;
  wire \$8 ;
  wire \$9 ;
  (* src = "/home/yym/workspace/fpga/./main.py:54" *)
  input clk;
  wire clk;
  (* src = "/home/yym/workspace/fpga/KnobControl.py:17" *)
  reg [31:0] cnt = 32'd0;
  (* src = "/home/yym/miniconda3/envs/amaranth/lib/python3.12/contextlib.py:144" *)
  reg fsm_state = 1'h1;
  (* src = "/home/yym/workspace/fpga/KnobControl.py:15" *)
  reg [1:0] last_stable_status = 2'h0;
  (* src = "/home/yym/workspace/fpga/KnobControl.py:16" *)
  reg [1:0] last_status = 2'h0;
  (* src = "/home/yym/workspace/fpga/KnobControl.py:7" *)
  output [1:0] out;
  reg [1:0] out = 2'h0;
  (* src = "/home/yym/workspace/fpga/./main.py:54" *)
  input rst;
  wire rst;
  (* src = "/home/yym/workspace/fpga/./main.py:28" *)
  input sample_period_control_knob_A;
  wire sample_period_control_knob_A;
  (* src = "/home/yym/workspace/fpga/./main.py:29" *)
  input sample_period_control_knob_B;
  wire sample_period_control_knob_B;
  (* src = "/home/yym/workspace/fpga/KnobControl.py:12" *)
  reg stable = 1'h0;
  (* src = "/home/yym/workspace/fpga/KnobControl.py:14" *)
  reg [1:0] stable_status = 2'h0;
  (* src = "/home/yym/workspace/fpga/KnobControl.py:13" *)
  reg [1:0] status = 2'h0;
  assign \$2  = \$1  + (* src = "/home/yym/workspace/fpga/KnobControl.py:20" *) sample_period_control_knob_B;
  assign \$3  = status != (* src = "/home/yym/workspace/fpga/KnobControl.py:25" *) last_status;
  assign \$4  = status == (* src = "/home/yym/workspace/fpga/KnobControl.py:29" *) last_status;
  assign \$5  = cnt + (* src = "/home/yym/workspace/fpga/KnobControl.py:30" *) 1'h1;
  assign \$6  = cnt >= (* src = "/home/yym/workspace/fpga/KnobControl.py:34" *) 20'hf4240;
  assign \$7  = stable_status == (* src = "/home/yym/workspace/fpga/KnobControl.py:44" *) 1'h1;
  assign \$8  = stable_status == (* src = "/home/yym/workspace/fpga/KnobControl.py:46" *) 2'h2;
  assign \$9  = stable_status == (* src = "/home/yym/workspace/fpga/KnobControl.py:49" *) 2'h3;
  assign \$10  = ! (* src = "/home/yym/workspace/fpga/KnobControl.py:51" *) stable_status;
  assign \$11  = stable_status == (* src = "/home/yym/workspace/fpga/KnobControl.py:54" *) 2'h2;
  assign \$12  = stable_status == (* src = "/home/yym/workspace/fpga/KnobControl.py:56" *) 1'h1;
  assign \$13  = ! (* src = "/home/yym/workspace/fpga/KnobControl.py:59" *) stable_status;
  assign \$14  = stable_status == (* src = "/home/yym/workspace/fpga/KnobControl.py:61" *) 2'h3;
  assign \$15  = | (* src = "/home/yym/workspace/fpga/KnobControl.py:68" *) out;
  assign \$16  = ! (* src = "/home/yym/miniconda3/envs/amaranth/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) fsm_state;
  (* src = "/home/yym/workspace/fpga/KnobControl.py:16" *)
  always @(posedge clk)
    last_status <= \$18 ;
  (* src = "/home/yym/workspace/fpga/KnobControl.py:13" *)
  always @(posedge clk)
    status <= \$19 ;
  (* src = "/home/yym/workspace/fpga/KnobControl.py:17" *)
  always @(posedge clk)
    cnt <= \$20 ;
  (* src = "/home/yym/miniconda3/envs/amaranth/lib/python3.12/contextlib.py:144" *)
  always @(posedge clk)
    fsm_state <= \$21 ;
  (* src = "/home/yym/workspace/fpga/KnobControl.py:12" *)
  always @(posedge clk)
    stable <= \$22 ;
  (* src = "/home/yym/workspace/fpga/KnobControl.py:14" *)
  always @(posedge clk)
    stable_status <= \$23 ;
  (* src = "/home/yym/workspace/fpga/KnobControl.py:7" *)
  always @(posedge clk)
    out <= \$24 ;
  (* src = "/home/yym/workspace/fpga/KnobControl.py:15" *)
  always @(posedge clk)
    last_stable_status <= \$25 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$4 ) begin end
    \$18  = status;
    if (rst) begin
      \$18  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$4 ) begin end
    \$19  = \$2 [1:0];
    if (rst) begin
      \$19  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$4 ) begin end
    \$20  = cnt;
    (* full_case = 32'd1 *)
    casez (fsm_state)
      1'h0:
          if (\$3 ) begin
            \$20  = 32'd0;
          end
      1'h1:
          (* full_case = 32'd1 *)
          if (\$4 ) begin
            \$20  = \$5 [31:0];
          end else begin
            \$20  = 32'd0;
          end
    endcase
    if (rst) begin
      \$20  = 32'd0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$4 ) begin end
    \$21  = fsm_state;
    (* full_case = 32'd1 *)
    casez (fsm_state)
      1'h0:
          if (\$3 ) begin
            \$21  = 1'h1;
          end
      1'h1:
          if (\$6 ) begin
            \$21  = 1'h0;
          end
    endcase
    if (rst) begin
      \$21  = 1'h1;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$4 ) begin end
    \$22  = stable;
    (* full_case = 32'd1 *)
    casez (fsm_state)
      1'h0:
          /* empty */;
      1'h1:
          if (\$6 ) begin
            \$22  = 1'h1;
          end
    endcase
    if (stable) begin
      \$22  = 1'h0;
    end
    if (rst) begin
      \$22  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$4 ) begin end
    \$23  = stable_status;
    (* full_case = 32'd1 *)
    casez (fsm_state)
      1'h0:
          /* empty */;
      1'h1:
          if (\$6 ) begin
            \$23  = status;
          end
    endcase
    if (rst) begin
      \$23  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$4 ) begin end
    \$24  = out;
    if (stable) begin
      (* full_case = 32'd1 *)
      casez (last_stable_status)
        2'h0:
            if (\$7 ) begin
              \$24  = 2'h1;
            end else if (\$8 ) begin
              \$24  = 2'h2;
            end
        2'h1:
            if (\$9 ) begin
              \$24  = 2'h1;
            end else if (\$10 ) begin
              \$24  = 2'h2;
            end
        2'h3:
            if (\$11 ) begin
              \$24  = 2'h1;
            end else if (\$12 ) begin
              \$24  = 2'h2;
            end
        2'h2:
            if (\$13 ) begin
              \$24  = 2'h1;
            end else if (\$14 ) begin
              \$24  = 2'h2;
            end
      endcase
    end
    if (\$15 ) begin
      \$24  = 2'h0;
    end
    if (rst) begin
      \$24  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$4 ) begin end
    \$25  = last_stable_status;
    if (stable) begin
      \$25  = stable_status;
    end
    if (rst) begin
      \$25  = 2'h0;
    end
  end
  assign \$1  = { sample_period_control_knob_A, 1'h0 };
  assign \$17  = fsm_state;
endmodule

(* src = "/home/yym/workspace/fpga/VGATiming.py:38" *)
(* generator = "Amaranth" *)
module \top.timing (pix_clk, visible, hsync, vsync, h_cnt, v_cnt, pix_rst);
  reg \$auto$verilog_backend.cc:2355:dump_module$5  = 0;
  wire \$1 ;
  wire \$10 ;
  wire \$11 ;
  wire \$12 ;
  reg [9:0] \$13 ;
  reg [9:0] \$14 ;
  wire \$2 ;
  wire [10:0] \$3 ;
  wire [10:0] \$4 ;
  wire \$5 ;
  wire \$6 ;
  wire \$7 ;
  wire \$8 ;
  wire \$9 ;
  (* src = "/home/yym/workspace/fpga/VGATiming.py:34" *)
  output [9:0] h_cnt;
  reg [9:0] h_cnt = 10'h000;
  (* src = "/home/yym/workspace/fpga/./main.py:14" *)
  output hsync;
  wire hsync;
  (* src = "/home/yym/workspace/fpga/./main.py:48" *)
  input pix_clk;
  wire pix_clk;
  (* src = "/home/yym/workspace/fpga/./main.py:48" *)
  input pix_rst;
  wire pix_rst;
  (* src = "/home/yym/workspace/fpga/VGATiming.py:35" *)
  output [9:0] v_cnt;
  reg [9:0] v_cnt = 10'h000;
  (* src = "/home/yym/workspace/fpga/./main.py:14" *)
  wire vga_hsync;
  (* src = "/home/yym/workspace/fpga/./main.py:15" *)
  wire vga_vsync;
  (* src = "/home/yym/workspace/fpga/VGATiming.py:32" *)
  output visible;
  wire visible;
  (* src = "/home/yym/workspace/fpga/./main.py:15" *)
  output vsync;
  wire vsync;
  (* init = 10'h000 *)
  (* src = "/home/yym/workspace/fpga/VGATiming.py:34" *)
  wire [9:0] x;
  (* init = 10'h000 *)
  (* src = "/home/yym/workspace/fpga/VGATiming.py:35" *)
  wire [9:0] y;
  assign \$1  = h_cnt == (* src = "/home/yym/workspace/fpga/VGATiming.py:47" *) 10'h31f;
  assign \$2  = v_cnt == (* src = "/home/yym/workspace/fpga/VGATiming.py:50" *) 10'h20c;
  assign \$3  = v_cnt + (* src = "/home/yym/workspace/fpga/VGATiming.py:53" *) 1'h1;
  assign \$4  = h_cnt + (* src = "/home/yym/workspace/fpga/VGATiming.py:56" *) 1'h1;
  assign \$5  = h_cnt < (* src = "/home/yym/workspace/fpga/VGATiming.py:63" *) 10'h280;
  assign \$6  = v_cnt < (* src = "/home/yym/workspace/fpga/VGATiming.py:64" *) 9'h1e0;
  assign visible = \$5  & (* src = "/home/yym/workspace/fpga/VGATiming.py:63" *) \$6 ;
  assign \$7  = h_cnt >= (* src = "/home/yym/workspace/fpga/VGATiming.py:76" *) 10'h290;
  assign \$8  = h_cnt < (* src = "/home/yym/workspace/fpga/VGATiming.py:76" *) 10'h2f0;
  assign \$9  = \$7  & (* src = "/home/yym/workspace/fpga/VGATiming.py:76" *) \$8 ;
  assign hsync = ~ (* src = "/home/yym/workspace/fpga/VGATiming.py:76" *) \$9 ;
  assign \$10  = v_cnt >= (* src = "/home/yym/workspace/fpga/VGATiming.py:77" *) 9'h1ea;
  assign \$11  = v_cnt < (* src = "/home/yym/workspace/fpga/VGATiming.py:77" *) 9'h1ec;
  assign \$12  = \$10  & (* src = "/home/yym/workspace/fpga/VGATiming.py:77" *) \$11 ;
  assign vsync = ~ (* src = "/home/yym/workspace/fpga/VGATiming.py:77" *) \$12 ;
  (* src = "/home/yym/workspace/fpga/VGATiming.py:43" *)
  always @(posedge pix_clk)
    h_cnt <= \$13 ;
  (* src = "/home/yym/workspace/fpga/VGATiming.py:44" *)
  always @(posedge pix_clk)
    v_cnt <= \$14 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$5 ) begin end
    (* full_case = 32'd1 *)
    if (\$1 ) begin
      \$13  = 10'h000;
    end else begin
      \$13  = \$4 [9:0];
    end
    if (pix_rst) begin
      \$13  = 10'h000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$5 ) begin end
    \$14  = v_cnt;
    if (\$1 ) begin
      (* full_case = 32'd1 *)
      if (\$2 ) begin
        \$14  = 10'h000;
      end else begin
        \$14  = \$3 [9:0];
      end
    end
    if (pix_rst) begin
      \$14  = 10'h000;
    end
  end
  assign x = h_cnt;
  assign y = v_cnt;
  assign vga_hsync = hsync;
  assign vga_vsync = vsync;
endmodule

(* src = "/home/yym/workspace/fpga/VGADisplay.py:15" *)
(* generator = "Amaranth" *)
module \top.vga_display (pix_rst, rst, pix_clk, visible, r_data, x, y, out, r, g, b, clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$6  = 0;
  wire \$1 ;
  wire [11:0] \$10 ;
  wire [12:0] \$11 ;
  wire [11:0] \$12 ;
  wire [12:0] \$13 ;
  wire \$14 ;
  wire \$15 ;
  reg [11:0] \$16 ;
  reg [11:0] \$17 ;
  wire \$2 ;
  wire \$3 ;
  wire [12:0] \$4 ;
  wire [11:0] \$5 ;
  wire [24:0] \$6 ;
  wire [25:0] \$7 ;
  wire \$8 ;
  wire \$9 ;
  (* src = "/home/yym/workspace/fpga/./main.py:19" *)
  output [3:0] b;
  reg [3:0] b;
  (* src = "/home/yym/workspace/fpga/./main.py:54" *)
  input clk;
  wire clk;
  (* src = "/home/yym/workspace/fpga/VGADisplay.py:22" *)
  wire [12:0] diff;
  (* src = "/home/yym/workspace/fpga/VGADisplay.py:21" *)
  reg [11:0] display_y = 12'h000;
  (* src = "/home/yym/workspace/fpga/./main.py:18" *)
  output [3:0] g;
  reg [3:0] g;
  (* src = "/home/yym/workspace/fpga/VGADisplay.py:24" *)
  reg [11:0] gain = 12'h010;
  (* src = "/home/yym/workspace/fpga/VGADisplay.py:20" *)
  wire grid;
  (* src = "/home/yym/workspace/fpga/KnobControl.py:7" *)
  input [1:0] out;
  wire [1:0] out;
  (* src = "/home/yym/workspace/fpga/./main.py:48" *)
  input pix_clk;
  wire pix_clk;
  (* src = "/home/yym/workspace/fpga/./main.py:48" *)
  input pix_rst;
  wire pix_rst;
  (* src = "/home/yym/workspace/fpga/./main.py:17" *)
  output [3:0] r;
  reg [3:0] r;
  (* src = "/home/yym/workspace/fpga/RAM.py:13" *)
  input [11:0] r_data;
  wire [11:0] r_data;
  (* src = "/home/yym/workspace/fpga/./main.py:54" *)
  input rst;
  wire rst;
  (* src = "/home/yym/workspace/fpga/./main.py:19" *)
  wire [3:0] vga_b;
  (* src = "/home/yym/workspace/fpga/./main.py:18" *)
  wire [3:0] vga_g;
  (* src = "/home/yym/workspace/fpga/./main.py:17" *)
  wire [3:0] vga_r;
  (* src = "/home/yym/workspace/fpga/VGATiming.py:32" *)
  input visible;
  wire visible;
  (* src = "/home/yym/workspace/fpga/VGATiming.py:34" *)
  input [9:0] x;
  wire [9:0] x;
  (* src = "/home/yym/workspace/fpga/VGATiming.py:35" *)
  input [9:0] y;
  wire [9:0] y;
  assign \$1  = ! (* src = "/home/yym/workspace/fpga/VGADisplay.py:26" *) x[5:0];
  assign \$2  = ! (* src = "/home/yym/workspace/fpga/VGADisplay.py:26" *) y[5:0];
  assign grid = \$1  | (* src = "/home/yym/workspace/fpga/VGADisplay.py:26" *) \$2 ;
  assign diff = r_data - (* src = "/home/yym/workspace/fpga/VGADisplay.py:29" *) 12'h800;
  assign \$3  = y == (* src = "/home/yym/workspace/fpga/VGADisplay.py:56" *) display_y;
  assign \$6  = $signed(\$4 ) * (* src = "/home/yym/workspace/fpga/VGADisplay.py:30" *) $signed({ 1'h0, \$5  });
  assign \$7  = $signed(9'h0f0) + (* src = "/home/yym/workspace/fpga/VGADisplay.py:30" *) $signed(\$6 );
  assign \$8  = out == (* src = "/home/yym/workspace/fpga/VGADisplay.py:39" *) 1'h1;
  assign \$9  = out == (* src = "/home/yym/workspace/fpga/VGADisplay.py:41" *) 2'h2;
  assign \$11  = gain + (* src = "/home/yym/workspace/fpga/VGADisplay.py:40" *) \$10 ;
  assign \$13  = gain - (* src = "/home/yym/workspace/fpga/VGADisplay.py:42" *) \$12 ;
  assign \$14  = gain < (* src = "/home/yym/workspace/fpga/VGADisplay.py:44" *) 3'h4;
  assign \$15  = gain > (* src = "/home/yym/workspace/fpga/VGADisplay.py:46" *) 9'h100;
  (* src = "/home/yym/workspace/fpga/VGADisplay.py:21" *)
  always @(posedge pix_clk)
    display_y <= \$16 ;
  (* src = "/home/yym/workspace/fpga/VGADisplay.py:24" *)
  always @(posedge clk)
    gain <= \$17 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$6 ) begin end
    r = 4'h0;
    if (visible) begin
      if (grid) begin
        r = 4'hf;
      end else if (\$3 ) begin
        r = 4'hf;
      end
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$6 ) begin end
    g = 4'h0;
    if (visible) begin
      if (grid) begin
        g = 4'hf;
      end else if (\$3 ) begin
        g = 4'hf;
      end
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$6 ) begin end
    b = 4'h0;
    if (visible) begin
      if (grid) begin
        b = 4'hf;
      end else if (\$3 ) begin
        b = 4'h0;
      end
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$6 ) begin end
    \$16  = \$7 [11:0];
    if (pix_rst) begin
      \$16  = 12'h000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$6 ) begin end
    \$17  = gain;
    if (\$8 ) begin
      \$17  = \$11 [11:0];
    end else if (\$9 ) begin
      \$17  = \$13 [11:0];
    end
    if (\$14 ) begin
      \$17  = 12'h004;
    end
    if (\$15 ) begin
      \$17  = 12'h100;
    end
    if (rst) begin
      \$17  = 12'h010;
    end
  end
  assign vga_r = r;
  assign vga_g = g;
  assign vga_b = b;
  assign \$4  = { diff[12], diff[12], diff[12], diff[12:3] };
  assign \$5  = { 4'h0, gain[11:4] };
  assign \$10  = { 2'h0, gain[11:2] };
  assign \$12  = { 2'h0, gain[11:2] };
endmodule

(* src = "/home/yym/workspace/fpga/WaveControl.py:16" *)
(* generator = "Amaranth" *)
module \top.wave_control (rst, adc_value, adc_ready, period, get_period_over, out, w_addr, w_en, w_data, clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$7  = 0;
  wire [32:0] \$1 ;
  wire \$10 ;
  wire \$11 ;
  wire [31:0] \$12 ;
  wire [32:0] \$13 ;
  wire [31:0] \$14 ;
  wire [32:0] \$15 ;
  reg [31:0] \$16 ;
  reg \$17 ;
  reg [31:0] \$18 ;
  reg [11:0] \$19 ;
  wire \$2 ;
  reg \$20 ;
  reg [11:0] \$21 ;
  reg [31:0] \$22 ;
  wire [32:0] \$3 ;
  wire [32:0] \$4 ;
  wire \$5 ;
  wire [12:0] \$6 ;
  wire [32:0] \$7 ;
  wire \$8 ;
  wire [31:0] \$9 ;
  (* src = "/home/yym/workspace/fpga/XADCModule.py:10" *)
  input adc_ready;
  wire adc_ready;
  (* src = "/home/yym/workspace/fpga/XADCModule.py:9" *)
  input [11:0] adc_value;
  wire [11:0] adc_value;
  (* src = "/home/yym/workspace/fpga/./main.py:54" *)
  input clk;
  wire clk;
  (* src = "/home/yym/workspace/fpga/PeriodDetector.py:10" *)
  input get_period_over;
  wire get_period_over;
  (* src = "/home/yym/workspace/fpga/KnobControl.py:7" *)
  input [1:0] out;
  wire [1:0] out;
  (* src = "/home/yym/workspace/fpga/PeriodDetector.py:9" *)
  input [31:0] period;
  wire [31:0] period;
  (* src = "/home/yym/workspace/fpga/WaveControl.py:20" *)
  reg [31:0] period_cnt = 32'd0;
  (* src = "/home/yym/workspace/fpga/WaveControl.py:21" *)
  reg period_overflow = 1'h0;
  (* src = "/home/yym/workspace/fpga/./main.py:54" *)
  input rst;
  wire rst;
  (* src = "/home/yym/workspace/fpga/WaveControl.py:23" *)
  reg [31:0] sample_clk = 32'd0;
  (* src = "/home/yym/workspace/fpga/WaveControl.py:13" *)
  reg [31:0] sample_period = 32'd100000;
  (* src = "/home/yym/workspace/fpga/WaveControl.py:11" *)
  output [11:0] w_addr;
  reg [11:0] w_addr = 12'h000;
  (* src = "/home/yym/workspace/fpga/WaveControl.py:12" *)
  output [11:0] w_data;
  reg [11:0] w_data = 12'h000;
  (* src = "/home/yym/workspace/fpga/WaveControl.py:10" *)
  output w_en;
  reg w_en = 1'h0;
  assign \$1  = period - (* src = "/home/yym/workspace/fpga/WaveControl.py:25" *) 1'h1;
  assign \$2  = period_cnt == (* src = "/home/yym/workspace/fpga/WaveControl.py:25" *) \$1 ;
  assign \$3  = period_cnt + (* src = "/home/yym/workspace/fpga/WaveControl.py:32" *) 1'h1;
  assign \$4  = sample_period - (* src = "/home/yym/workspace/fpga/WaveControl.py:36" *) 1'h1;
  assign \$5  = sample_clk == (* src = "/home/yym/workspace/fpga/WaveControl.py:36" *) \$4 ;
  assign \$6  = w_addr + (* src = "/home/yym/workspace/fpga/WaveControl.py:39" *) 1'h1;
  assign \$7  = sample_clk + (* src = "/home/yym/workspace/fpga/WaveControl.py:42" *) 1'h1;
  assign \$8  = w_addr >= (* src = "/home/yym/workspace/fpga/WaveControl.py:44" *) 10'h280;
  assign \$10  = out == (* src = "/home/yym/workspace/fpga/WaveControl.py:62" *) 1'h1;
  assign \$11  = out == (* src = "/home/yym/workspace/fpga/WaveControl.py:64" *) 2'h2;
  assign \$13  = sample_period + (* src = "/home/yym/workspace/fpga/WaveControl.py:63" *) \$12 ;
  assign \$15  = sample_period - (* src = "/home/yym/workspace/fpga/WaveControl.py:65" *) \$14 ;
  (* src = "/home/yym/workspace/fpga/WaveControl.py:20" *)
  always @(posedge clk)
    period_cnt <= \$16 ;
  (* src = "/home/yym/workspace/fpga/WaveControl.py:21" *)
  always @(posedge clk)
    period_overflow <= \$17 ;
  (* src = "/home/yym/workspace/fpga/WaveControl.py:23" *)
  always @(posedge clk)
    sample_clk <= \$18 ;
  (* src = "/home/yym/workspace/fpga/WaveControl.py:11" *)
  always @(posedge clk)
    w_addr <= \$19 ;
  (* src = "/home/yym/workspace/fpga/WaveControl.py:10" *)
  always @(posedge clk)
    w_en <= \$20 ;
  (* src = "/home/yym/workspace/fpga/WaveControl.py:12" *)
  always @(posedge clk)
    w_data <= \$21 ;
  (* src = "/home/yym/workspace/fpga/WaveControl.py:13" *)
  always @(posedge clk)
    sample_period <= \$22 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$7 ) begin end
    (* full_case = 32'd1 *)
    if (\$2 ) begin
      \$16  = 32'd0;
    end else begin
      \$16  = \$3 [31:0];
    end
    if (rst) begin
      \$16  = 32'd0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$7 ) begin end
    (* full_case = 32'd1 *)
    if (\$2 ) begin
      \$17  = 1'h1;
    end else begin
      \$17  = 1'h0;
    end
    if (rst) begin
      \$17  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$7 ) begin end
    (* full_case = 32'd1 *)
    if (\$5 ) begin
      \$18  = 32'd0;
    end else begin
      \$18  = \$7 [31:0];
    end
    if (rst) begin
      \$18  = 32'd0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$7 ) begin end
    \$19  = w_addr;
    if (\$5 ) begin
      \$19  = \$6 [11:0];
    end
    if (\$8 ) begin
      (* full_case = 32'd1 *)
      if (period_overflow) begin
        \$19  = 12'h000;
      end else begin
        \$19  = 12'h280;
      end
    end
    if (rst) begin
      \$19  = 12'h000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$7 ) begin end
    \$20  = w_en;
    if (\$8 ) begin
    end else if (adc_ready) begin
      \$20  = 1'h1;
    end
    if (w_en) begin
      \$20  = 1'h0;
    end
    if (rst) begin
      \$20  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$7 ) begin end
    \$21  = w_data;
    if (\$8 ) begin
    end else if (adc_ready) begin
      \$21  = adc_value;
    end
    if (rst) begin
      \$21  = 12'h000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$7 ) begin end
    \$22  = sample_period;
    if (get_period_over) begin
      \$22  = \$9 ;
    end
    if (\$10 ) begin
      \$22  = \$13 [31:0];
    end else if (\$11 ) begin
      \$22  = \$15 [31:0];
    end
    if (rst) begin
      \$22  = 32'd100000;
    end
  end
  assign \$9  = { 7'h00, period[31:7] };
  assign \$12  = { 4'h0, sample_period[31:4] };
  assign \$14  = { 4'h0, sample_period[31:4] };
endmodule

(* src = "/home/yym/workspace/fpga/XADCModule.py:13" *)
(* generator = "Amaranth" *)
module \top.xadc (vauxp1, vauxn1, rst, adc_value, adc_ready, clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$8  = 0;
  wire \$1 ;
  reg [11:0] \$2 ;
  reg \$3 ;
  (* src = "/home/yym/workspace/fpga/XADCModule.py:10" *)
  output adc_ready;
  reg adc_ready = 1'h0;
  (* src = "/home/yym/workspace/fpga/XADCModule.py:9" *)
  output [11:0] adc_value;
  reg [11:0] adc_value = 12'h000;
  (* src = "/home/yym/workspace/fpga/./main.py:21" *)
  input clk;
  wire clk;
  (* src = "/home/yym/workspace/fpga/./main.py:21" *)
  wire \clk$6 ;
  (* src = "/home/yym/workspace/fpga/XADCModule.py:16" *)
  wire drdy;
  (* src = "/home/yym/workspace/fpga/./main.py:54" *)
  input rst;
  wire rst;
  (* src = "/home/yym/workspace/fpga/./main.py:24" *)
  input vauxn1;
  wire vauxn1;
  (* src = "/home/yym/workspace/fpga/./main.py:23" *)
  input vauxp1;
  wire vauxp1;
  (* src = "/home/yym/workspace/fpga/XADCModule.py:15" *)
  wire [15:0] xadc_data;
  (* src = "/home/yym/workspace/fpga/XADCModule.py:9" *)
  always @(posedge clk)
    adc_value <= \$2 ;
  (* src = "/home/yym/workspace/fpga/XADCModule.py:10" *)
  always @(posedge clk)
    adc_ready <= \$3 ;
  (* src = "/home/yym/workspace/fpga/XADCModule.py:19" *)
  xadc_wiz_0 u_xadc (
    .daddr_in(7'h11),
    .dclk_in(clk),
    .den_in(\$1 ),
    .di_in(16'h0000),
    .do_out(xadc_data),
    .drdy_out(drdy),
    .dwe_in(1'h0),
    .eoc_out(\$1 ),
    .reset_in(1'h0),
    .vauxn1(vauxn1),
    .vauxp1(vauxp1),
    .vn_in(1'h0),
    .vp_in(1'h0)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$8 ) begin end
    \$2  = adc_value;
    if (drdy) begin
      \$2  = xadc_data[15:4];
    end
    if (rst) begin
      \$2  = 12'h000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$8 ) begin end
    (* full_case = 32'd1 *)
    if (drdy) begin
      \$3  = 1'h1;
    end else begin
      \$3  = 1'h0;
    end
    if (rst) begin
      \$3  = 1'h0;
    end
  end
  assign \clk$6  = clk;
endmodule
