/* Generated by Amaranth Yosys 0.50 (PyPI ver 0.50.0.0.post124, git sha1 b5170e139) */

(* top =  1  *)
(* src = "/home/yym/workspace/fpga/./main.py:22" *)
(* generator = "Amaranth" *)
module top(rst, vauxp1, vauxn1, vga_hsync, vga_vsync, vga_r, vga_g, vga_b, clk);
  wire \$1 ;
  (* src = "/home/yym/workspace/fpga/XADCModule.py:9" *)
  wire [11:0] adc_value;
  (* src = "/home/yym/workspace/fpga/./main.py:41" *)
  input clk;
  wire clk;
  (* src = "/home/yym/workspace/fpga/./main.py:41" *)
  wire \clk$12 ;
  (* src = "/home/yym/workspace/fpga/./main.py:26" *)
  wire clk_25m;
  (* src = "/home/yym/workspace/fpga/./main.py:35" *)
  wire pix_clk;
  (* src = "/home/yym/workspace/fpga/./main.py:35" *)
  wire pix_rst;
  (* src = "/home/yym/workspace/fpga/RAM.py:14" *)
  wire [8:0] r_data;
  (* src = "/home/yym/workspace/fpga/./main.py:15" *)
  input rst;
  wire rst;
  (* src = "/home/yym/workspace/fpga/./main.py:41" *)
  wire \rst$13 ;
  (* src = "/home/yym/workspace/fpga/./main.py:19" *)
  input vauxn1;
  wire vauxn1;
  (* src = "/home/yym/workspace/fpga/./main.py:18" *)
  input vauxp1;
  wire vauxp1;
  (* src = "/home/yym/workspace/fpga/./main.py:14" *)
  output [3:0] vga_b;
  wire [3:0] vga_b;
  (* src = "/home/yym/workspace/fpga/./main.py:13" *)
  output [3:0] vga_g;
  wire [3:0] vga_g;
  (* src = "/home/yym/workspace/fpga/./main.py:9" *)
  output vga_hsync;
  wire vga_hsync;
  (* src = "/home/yym/workspace/fpga/./main.py:12" *)
  output [3:0] vga_r;
  wire [3:0] vga_r;
  (* src = "/home/yym/workspace/fpga/./main.py:10" *)
  output vga_vsync;
  wire vga_vsync;
  (* src = "/home/yym/workspace/fpga/VGATiming.py:32" *)
  wire visible;
  (* src = "/home/yym/workspace/fpga/RAM.py:16" *)
  wire [9:0] w_addr;
  (* src = "/home/yym/workspace/fpga/VGATiming.py:34" *)
  wire [9:0] x;
  (* src = "/home/yym/workspace/fpga/VGATiming.py:35" *)
  wire [9:0] y;
  assign pix_rst = ~ (* src = "/home/yym/workspace/fpga/./main.py:38" *) rst;
  assign \rst$13  = ~ (* src = "/home/yym/workspace/fpga/./main.py:44" *) rst;
  assign \$1  = ~ (* src = "/home/yym/workspace/fpga/./main.py:31" *) rst;
  (* src = "/home/yym/workspace/fpga/./main.py:28" *)
  dcm_25m dcm_25m (
    .clk_in1(clk),
    .clk_out1(pix_clk),
    .reset(\$1 )
  );
  (* src = "/home/yym/workspace/fpga/./main.py:55" *)
  \top.my_ram  my_ram (
    .adc_value(adc_value),
    .clk(clk),
    .r_data(r_data),
    .rd__addr(x),
    .rd__en(visible),
    .rst(\rst$13 ),
    .w_addr(w_addr)
  );
  (* src = "/home/yym/workspace/fpga/./main.py:49" *)
  \top.timing  timing (
    .h_cnt(x),
    .hsync(vga_hsync),
    .pix_clk(pix_clk),
    .pix_rst(pix_rst),
    .v_cnt(y),
    .visible(visible),
    .vsync(vga_vsync)
  );
  (* src = "/home/yym/workspace/fpga/./main.py:58" *)
  \top.vga_display  vga_display (
    .b(vga_b),
    .g(vga_g),
    .r(vga_r),
    .r_data(r_data),
    .visible(visible),
    .w_addr(w_addr),
    .x(x),
    .y(y)
  );
  (* src = "/home/yym/workspace/fpga/./main.py:52" *)
  \top.xadc  xadc (
    .adc_value(adc_value),
    .clk(clk),
    .rst(\rst$13 ),
    .vauxn1(vauxn1),
    .vauxp1(vauxp1)
  );
  assign clk_25m = pix_clk;
  assign \clk$12  = clk;
endmodule

(* src = "/home/yym/workspace/fpga/RAM.py:19" *)
(* generator = "Amaranth" *)
module \top.my_ram (rst, rd__en, r_data, rd__addr, adc_value, w_addr, clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$1  = 0;
  wire \$1 ;
  wire [17:0] \$2 ;
  wire \$3 ;
  wire [10:0] \$4 ;
  wire [11:0] \$5 ;
  reg [16:0] \$6 ;
  reg \$7 ;
  reg [9:0] \$8 ;
  (* src = "/home/yym/workspace/fpga/XADCModule.py:9" *)
  input [11:0] adc_value;
  wire [11:0] adc_value;
  (* src = "/home/yym/workspace/fpga/./main.py:41" *)
  input clk;
  wire clk;
  (* src = "/home/yym/workspace/fpga/RAM.py:14" *)
  output [8:0] r_data;
  wire [8:0] r_data;
  (* src = "/home/yym/workspace/fpga/VGATiming.py:34" *)
  input [9:0] rd__addr;
  wire [9:0] rd__addr;
  (* src = "/home/yym/miniconda3/envs/amaranth/lib/python3.12/site-packages/amaranth/lib/memory.py:241" *)
  wire [9:0] rd__data;
  (* src = "/home/yym/workspace/fpga/VGATiming.py:32" *)
  input rd__en;
  wire rd__en;
  (* src = "/home/yym/workspace/fpga/./main.py:41" *)
  input rst;
  wire rst;
  (* src = "/home/yym/workspace/fpga/RAM.py:30" *)
  reg [16:0] sample_clk = 17'h00000;
  (* src = "/home/yym/workspace/fpga/VGATiming.py:32" *)
  wire visible;
  (* src = "/home/yym/miniconda3/envs/amaranth/lib/python3.12/site-packages/amaranth/lib/memory.py:401" *)
  output [9:0] w_addr;
  reg [9:0] w_addr = 10'h000;
  (* src = "/home/yym/workspace/fpga/RAM.py:10" *)
  reg w_en = 1'h0;
  (* init = 10'h000 *)
  (* src = "/home/yym/miniconda3/envs/amaranth/lib/python3.12/site-packages/amaranth/lib/memory.py:401" *)
  wire [9:0] wr__addr;
  (* src = "/home/yym/miniconda3/envs/amaranth/lib/python3.12/site-packages/amaranth/lib/memory.py:402" *)
  wire [9:0] wr__data;
  (* init = 1'h0 *)
  (* src = "/home/yym/miniconda3/envs/amaranth/lib/python3.12/site-packages/amaranth/lib/memory.py:400" *)
  wire wr__en;
  (* src = "/home/yym/workspace/fpga/VGATiming.py:34" *)
  wire [9:0] x;
  (* src = "/home/yym/workspace/fpga/RAM.py:21" *)
  reg [9:0] ram [639:0];
  initial begin
    ram[0] = 10'h000;
    ram[1] = 10'h000;
    ram[2] = 10'h000;
    ram[3] = 10'h000;
    ram[4] = 10'h000;
    ram[5] = 10'h000;
    ram[6] = 10'h000;
    ram[7] = 10'h000;
    ram[8] = 10'h000;
    ram[9] = 10'h000;
    ram[10] = 10'h000;
    ram[11] = 10'h000;
    ram[12] = 10'h000;
    ram[13] = 10'h000;
    ram[14] = 10'h000;
    ram[15] = 10'h000;
    ram[16] = 10'h000;
    ram[17] = 10'h000;
    ram[18] = 10'h000;
    ram[19] = 10'h000;
    ram[20] = 10'h000;
    ram[21] = 10'h000;
    ram[22] = 10'h000;
    ram[23] = 10'h000;
    ram[24] = 10'h000;
    ram[25] = 10'h000;
    ram[26] = 10'h000;
    ram[27] = 10'h000;
    ram[28] = 10'h000;
    ram[29] = 10'h000;
    ram[30] = 10'h000;
    ram[31] = 10'h000;
    ram[32] = 10'h000;
    ram[33] = 10'h000;
    ram[34] = 10'h000;
    ram[35] = 10'h000;
    ram[36] = 10'h000;
    ram[37] = 10'h000;
    ram[38] = 10'h000;
    ram[39] = 10'h000;
    ram[40] = 10'h000;
    ram[41] = 10'h000;
    ram[42] = 10'h000;
    ram[43] = 10'h000;
    ram[44] = 10'h000;
    ram[45] = 10'h000;
    ram[46] = 10'h000;
    ram[47] = 10'h000;
    ram[48] = 10'h000;
    ram[49] = 10'h000;
    ram[50] = 10'h000;
    ram[51] = 10'h000;
    ram[52] = 10'h000;
    ram[53] = 10'h000;
    ram[54] = 10'h000;
    ram[55] = 10'h000;
    ram[56] = 10'h000;
    ram[57] = 10'h000;
    ram[58] = 10'h000;
    ram[59] = 10'h000;
    ram[60] = 10'h000;
    ram[61] = 10'h000;
    ram[62] = 10'h000;
    ram[63] = 10'h000;
    ram[64] = 10'h000;
    ram[65] = 10'h000;
    ram[66] = 10'h000;
    ram[67] = 10'h000;
    ram[68] = 10'h000;
    ram[69] = 10'h000;
    ram[70] = 10'h000;
    ram[71] = 10'h000;
    ram[72] = 10'h000;
    ram[73] = 10'h000;
    ram[74] = 10'h000;
    ram[75] = 10'h000;
    ram[76] = 10'h000;
    ram[77] = 10'h000;
    ram[78] = 10'h000;
    ram[79] = 10'h000;
    ram[80] = 10'h000;
    ram[81] = 10'h000;
    ram[82] = 10'h000;
    ram[83] = 10'h000;
    ram[84] = 10'h000;
    ram[85] = 10'h000;
    ram[86] = 10'h000;
    ram[87] = 10'h000;
    ram[88] = 10'h000;
    ram[89] = 10'h000;
    ram[90] = 10'h000;
    ram[91] = 10'h000;
    ram[92] = 10'h000;
    ram[93] = 10'h000;
    ram[94] = 10'h000;
    ram[95] = 10'h000;
    ram[96] = 10'h000;
    ram[97] = 10'h000;
    ram[98] = 10'h000;
    ram[99] = 10'h000;
    ram[100] = 10'h000;
    ram[101] = 10'h000;
    ram[102] = 10'h000;
    ram[103] = 10'h000;
    ram[104] = 10'h000;
    ram[105] = 10'h000;
    ram[106] = 10'h000;
    ram[107] = 10'h000;
    ram[108] = 10'h000;
    ram[109] = 10'h000;
    ram[110] = 10'h000;
    ram[111] = 10'h000;
    ram[112] = 10'h000;
    ram[113] = 10'h000;
    ram[114] = 10'h000;
    ram[115] = 10'h000;
    ram[116] = 10'h000;
    ram[117] = 10'h000;
    ram[118] = 10'h000;
    ram[119] = 10'h000;
    ram[120] = 10'h000;
    ram[121] = 10'h000;
    ram[122] = 10'h000;
    ram[123] = 10'h000;
    ram[124] = 10'h000;
    ram[125] = 10'h000;
    ram[126] = 10'h000;
    ram[127] = 10'h000;
    ram[128] = 10'h000;
    ram[129] = 10'h000;
    ram[130] = 10'h000;
    ram[131] = 10'h000;
    ram[132] = 10'h000;
    ram[133] = 10'h000;
    ram[134] = 10'h000;
    ram[135] = 10'h000;
    ram[136] = 10'h000;
    ram[137] = 10'h000;
    ram[138] = 10'h000;
    ram[139] = 10'h000;
    ram[140] = 10'h000;
    ram[141] = 10'h000;
    ram[142] = 10'h000;
    ram[143] = 10'h000;
    ram[144] = 10'h000;
    ram[145] = 10'h000;
    ram[146] = 10'h000;
    ram[147] = 10'h000;
    ram[148] = 10'h000;
    ram[149] = 10'h000;
    ram[150] = 10'h000;
    ram[151] = 10'h000;
    ram[152] = 10'h000;
    ram[153] = 10'h000;
    ram[154] = 10'h000;
    ram[155] = 10'h000;
    ram[156] = 10'h000;
    ram[157] = 10'h000;
    ram[158] = 10'h000;
    ram[159] = 10'h000;
    ram[160] = 10'h000;
    ram[161] = 10'h000;
    ram[162] = 10'h000;
    ram[163] = 10'h000;
    ram[164] = 10'h000;
    ram[165] = 10'h000;
    ram[166] = 10'h000;
    ram[167] = 10'h000;
    ram[168] = 10'h000;
    ram[169] = 10'h000;
    ram[170] = 10'h000;
    ram[171] = 10'h000;
    ram[172] = 10'h000;
    ram[173] = 10'h000;
    ram[174] = 10'h000;
    ram[175] = 10'h000;
    ram[176] = 10'h000;
    ram[177] = 10'h000;
    ram[178] = 10'h000;
    ram[179] = 10'h000;
    ram[180] = 10'h000;
    ram[181] = 10'h000;
    ram[182] = 10'h000;
    ram[183] = 10'h000;
    ram[184] = 10'h000;
    ram[185] = 10'h000;
    ram[186] = 10'h000;
    ram[187] = 10'h000;
    ram[188] = 10'h000;
    ram[189] = 10'h000;
    ram[190] = 10'h000;
    ram[191] = 10'h000;
    ram[192] = 10'h000;
    ram[193] = 10'h000;
    ram[194] = 10'h000;
    ram[195] = 10'h000;
    ram[196] = 10'h000;
    ram[197] = 10'h000;
    ram[198] = 10'h000;
    ram[199] = 10'h000;
    ram[200] = 10'h000;
    ram[201] = 10'h000;
    ram[202] = 10'h000;
    ram[203] = 10'h000;
    ram[204] = 10'h000;
    ram[205] = 10'h000;
    ram[206] = 10'h000;
    ram[207] = 10'h000;
    ram[208] = 10'h000;
    ram[209] = 10'h000;
    ram[210] = 10'h000;
    ram[211] = 10'h000;
    ram[212] = 10'h000;
    ram[213] = 10'h000;
    ram[214] = 10'h000;
    ram[215] = 10'h000;
    ram[216] = 10'h000;
    ram[217] = 10'h000;
    ram[218] = 10'h000;
    ram[219] = 10'h000;
    ram[220] = 10'h000;
    ram[221] = 10'h000;
    ram[222] = 10'h000;
    ram[223] = 10'h000;
    ram[224] = 10'h000;
    ram[225] = 10'h000;
    ram[226] = 10'h000;
    ram[227] = 10'h000;
    ram[228] = 10'h000;
    ram[229] = 10'h000;
    ram[230] = 10'h000;
    ram[231] = 10'h000;
    ram[232] = 10'h000;
    ram[233] = 10'h000;
    ram[234] = 10'h000;
    ram[235] = 10'h000;
    ram[236] = 10'h000;
    ram[237] = 10'h000;
    ram[238] = 10'h000;
    ram[239] = 10'h000;
    ram[240] = 10'h000;
    ram[241] = 10'h000;
    ram[242] = 10'h000;
    ram[243] = 10'h000;
    ram[244] = 10'h000;
    ram[245] = 10'h000;
    ram[246] = 10'h000;
    ram[247] = 10'h000;
    ram[248] = 10'h000;
    ram[249] = 10'h000;
    ram[250] = 10'h000;
    ram[251] = 10'h000;
    ram[252] = 10'h000;
    ram[253] = 10'h000;
    ram[254] = 10'h000;
    ram[255] = 10'h000;
    ram[256] = 10'h000;
    ram[257] = 10'h000;
    ram[258] = 10'h000;
    ram[259] = 10'h000;
    ram[260] = 10'h000;
    ram[261] = 10'h000;
    ram[262] = 10'h000;
    ram[263] = 10'h000;
    ram[264] = 10'h000;
    ram[265] = 10'h000;
    ram[266] = 10'h000;
    ram[267] = 10'h000;
    ram[268] = 10'h000;
    ram[269] = 10'h000;
    ram[270] = 10'h000;
    ram[271] = 10'h000;
    ram[272] = 10'h000;
    ram[273] = 10'h000;
    ram[274] = 10'h000;
    ram[275] = 10'h000;
    ram[276] = 10'h000;
    ram[277] = 10'h000;
    ram[278] = 10'h000;
    ram[279] = 10'h000;
    ram[280] = 10'h000;
    ram[281] = 10'h000;
    ram[282] = 10'h000;
    ram[283] = 10'h000;
    ram[284] = 10'h000;
    ram[285] = 10'h000;
    ram[286] = 10'h000;
    ram[287] = 10'h000;
    ram[288] = 10'h000;
    ram[289] = 10'h000;
    ram[290] = 10'h000;
    ram[291] = 10'h000;
    ram[292] = 10'h000;
    ram[293] = 10'h000;
    ram[294] = 10'h000;
    ram[295] = 10'h000;
    ram[296] = 10'h000;
    ram[297] = 10'h000;
    ram[298] = 10'h000;
    ram[299] = 10'h000;
    ram[300] = 10'h000;
    ram[301] = 10'h000;
    ram[302] = 10'h000;
    ram[303] = 10'h000;
    ram[304] = 10'h000;
    ram[305] = 10'h000;
    ram[306] = 10'h000;
    ram[307] = 10'h000;
    ram[308] = 10'h000;
    ram[309] = 10'h000;
    ram[310] = 10'h000;
    ram[311] = 10'h000;
    ram[312] = 10'h000;
    ram[313] = 10'h000;
    ram[314] = 10'h000;
    ram[315] = 10'h000;
    ram[316] = 10'h000;
    ram[317] = 10'h000;
    ram[318] = 10'h000;
    ram[319] = 10'h000;
    ram[320] = 10'h000;
    ram[321] = 10'h000;
    ram[322] = 10'h000;
    ram[323] = 10'h000;
    ram[324] = 10'h000;
    ram[325] = 10'h000;
    ram[326] = 10'h000;
    ram[327] = 10'h000;
    ram[328] = 10'h000;
    ram[329] = 10'h000;
    ram[330] = 10'h000;
    ram[331] = 10'h000;
    ram[332] = 10'h000;
    ram[333] = 10'h000;
    ram[334] = 10'h000;
    ram[335] = 10'h000;
    ram[336] = 10'h000;
    ram[337] = 10'h000;
    ram[338] = 10'h000;
    ram[339] = 10'h000;
    ram[340] = 10'h000;
    ram[341] = 10'h000;
    ram[342] = 10'h000;
    ram[343] = 10'h000;
    ram[344] = 10'h000;
    ram[345] = 10'h000;
    ram[346] = 10'h000;
    ram[347] = 10'h000;
    ram[348] = 10'h000;
    ram[349] = 10'h000;
    ram[350] = 10'h000;
    ram[351] = 10'h000;
    ram[352] = 10'h000;
    ram[353] = 10'h000;
    ram[354] = 10'h000;
    ram[355] = 10'h000;
    ram[356] = 10'h000;
    ram[357] = 10'h000;
    ram[358] = 10'h000;
    ram[359] = 10'h000;
    ram[360] = 10'h000;
    ram[361] = 10'h000;
    ram[362] = 10'h000;
    ram[363] = 10'h000;
    ram[364] = 10'h000;
    ram[365] = 10'h000;
    ram[366] = 10'h000;
    ram[367] = 10'h000;
    ram[368] = 10'h000;
    ram[369] = 10'h000;
    ram[370] = 10'h000;
    ram[371] = 10'h000;
    ram[372] = 10'h000;
    ram[373] = 10'h000;
    ram[374] = 10'h000;
    ram[375] = 10'h000;
    ram[376] = 10'h000;
    ram[377] = 10'h000;
    ram[378] = 10'h000;
    ram[379] = 10'h000;
    ram[380] = 10'h000;
    ram[381] = 10'h000;
    ram[382] = 10'h000;
    ram[383] = 10'h000;
    ram[384] = 10'h000;
    ram[385] = 10'h000;
    ram[386] = 10'h000;
    ram[387] = 10'h000;
    ram[388] = 10'h000;
    ram[389] = 10'h000;
    ram[390] = 10'h000;
    ram[391] = 10'h000;
    ram[392] = 10'h000;
    ram[393] = 10'h000;
    ram[394] = 10'h000;
    ram[395] = 10'h000;
    ram[396] = 10'h000;
    ram[397] = 10'h000;
    ram[398] = 10'h000;
    ram[399] = 10'h000;
    ram[400] = 10'h000;
    ram[401] = 10'h000;
    ram[402] = 10'h000;
    ram[403] = 10'h000;
    ram[404] = 10'h000;
    ram[405] = 10'h000;
    ram[406] = 10'h000;
    ram[407] = 10'h000;
    ram[408] = 10'h000;
    ram[409] = 10'h000;
    ram[410] = 10'h000;
    ram[411] = 10'h000;
    ram[412] = 10'h000;
    ram[413] = 10'h000;
    ram[414] = 10'h000;
    ram[415] = 10'h000;
    ram[416] = 10'h000;
    ram[417] = 10'h000;
    ram[418] = 10'h000;
    ram[419] = 10'h000;
    ram[420] = 10'h000;
    ram[421] = 10'h000;
    ram[422] = 10'h000;
    ram[423] = 10'h000;
    ram[424] = 10'h000;
    ram[425] = 10'h000;
    ram[426] = 10'h000;
    ram[427] = 10'h000;
    ram[428] = 10'h000;
    ram[429] = 10'h000;
    ram[430] = 10'h000;
    ram[431] = 10'h000;
    ram[432] = 10'h000;
    ram[433] = 10'h000;
    ram[434] = 10'h000;
    ram[435] = 10'h000;
    ram[436] = 10'h000;
    ram[437] = 10'h000;
    ram[438] = 10'h000;
    ram[439] = 10'h000;
    ram[440] = 10'h000;
    ram[441] = 10'h000;
    ram[442] = 10'h000;
    ram[443] = 10'h000;
    ram[444] = 10'h000;
    ram[445] = 10'h000;
    ram[446] = 10'h000;
    ram[447] = 10'h000;
    ram[448] = 10'h000;
    ram[449] = 10'h000;
    ram[450] = 10'h000;
    ram[451] = 10'h000;
    ram[452] = 10'h000;
    ram[453] = 10'h000;
    ram[454] = 10'h000;
    ram[455] = 10'h000;
    ram[456] = 10'h000;
    ram[457] = 10'h000;
    ram[458] = 10'h000;
    ram[459] = 10'h000;
    ram[460] = 10'h000;
    ram[461] = 10'h000;
    ram[462] = 10'h000;
    ram[463] = 10'h000;
    ram[464] = 10'h000;
    ram[465] = 10'h000;
    ram[466] = 10'h000;
    ram[467] = 10'h000;
    ram[468] = 10'h000;
    ram[469] = 10'h000;
    ram[470] = 10'h000;
    ram[471] = 10'h000;
    ram[472] = 10'h000;
    ram[473] = 10'h000;
    ram[474] = 10'h000;
    ram[475] = 10'h000;
    ram[476] = 10'h000;
    ram[477] = 10'h000;
    ram[478] = 10'h000;
    ram[479] = 10'h000;
    ram[480] = 10'h000;
    ram[481] = 10'h000;
    ram[482] = 10'h000;
    ram[483] = 10'h000;
    ram[484] = 10'h000;
    ram[485] = 10'h000;
    ram[486] = 10'h000;
    ram[487] = 10'h000;
    ram[488] = 10'h000;
    ram[489] = 10'h000;
    ram[490] = 10'h000;
    ram[491] = 10'h000;
    ram[492] = 10'h000;
    ram[493] = 10'h000;
    ram[494] = 10'h000;
    ram[495] = 10'h000;
    ram[496] = 10'h000;
    ram[497] = 10'h000;
    ram[498] = 10'h000;
    ram[499] = 10'h000;
    ram[500] = 10'h000;
    ram[501] = 10'h000;
    ram[502] = 10'h000;
    ram[503] = 10'h000;
    ram[504] = 10'h000;
    ram[505] = 10'h000;
    ram[506] = 10'h000;
    ram[507] = 10'h000;
    ram[508] = 10'h000;
    ram[509] = 10'h000;
    ram[510] = 10'h000;
    ram[511] = 10'h000;
    ram[512] = 10'h000;
    ram[513] = 10'h000;
    ram[514] = 10'h000;
    ram[515] = 10'h000;
    ram[516] = 10'h000;
    ram[517] = 10'h000;
    ram[518] = 10'h000;
    ram[519] = 10'h000;
    ram[520] = 10'h000;
    ram[521] = 10'h000;
    ram[522] = 10'h000;
    ram[523] = 10'h000;
    ram[524] = 10'h000;
    ram[525] = 10'h000;
    ram[526] = 10'h000;
    ram[527] = 10'h000;
    ram[528] = 10'h000;
    ram[529] = 10'h000;
    ram[530] = 10'h000;
    ram[531] = 10'h000;
    ram[532] = 10'h000;
    ram[533] = 10'h000;
    ram[534] = 10'h000;
    ram[535] = 10'h000;
    ram[536] = 10'h000;
    ram[537] = 10'h000;
    ram[538] = 10'h000;
    ram[539] = 10'h000;
    ram[540] = 10'h000;
    ram[541] = 10'h000;
    ram[542] = 10'h000;
    ram[543] = 10'h000;
    ram[544] = 10'h000;
    ram[545] = 10'h000;
    ram[546] = 10'h000;
    ram[547] = 10'h000;
    ram[548] = 10'h000;
    ram[549] = 10'h000;
    ram[550] = 10'h000;
    ram[551] = 10'h000;
    ram[552] = 10'h000;
    ram[553] = 10'h000;
    ram[554] = 10'h000;
    ram[555] = 10'h000;
    ram[556] = 10'h000;
    ram[557] = 10'h000;
    ram[558] = 10'h000;
    ram[559] = 10'h000;
    ram[560] = 10'h000;
    ram[561] = 10'h000;
    ram[562] = 10'h000;
    ram[563] = 10'h000;
    ram[564] = 10'h000;
    ram[565] = 10'h000;
    ram[566] = 10'h000;
    ram[567] = 10'h000;
    ram[568] = 10'h000;
    ram[569] = 10'h000;
    ram[570] = 10'h000;
    ram[571] = 10'h000;
    ram[572] = 10'h000;
    ram[573] = 10'h000;
    ram[574] = 10'h000;
    ram[575] = 10'h000;
    ram[576] = 10'h000;
    ram[577] = 10'h000;
    ram[578] = 10'h000;
    ram[579] = 10'h000;
    ram[580] = 10'h000;
    ram[581] = 10'h000;
    ram[582] = 10'h000;
    ram[583] = 10'h000;
    ram[584] = 10'h000;
    ram[585] = 10'h000;
    ram[586] = 10'h000;
    ram[587] = 10'h000;
    ram[588] = 10'h000;
    ram[589] = 10'h000;
    ram[590] = 10'h000;
    ram[591] = 10'h000;
    ram[592] = 10'h000;
    ram[593] = 10'h000;
    ram[594] = 10'h000;
    ram[595] = 10'h000;
    ram[596] = 10'h000;
    ram[597] = 10'h000;
    ram[598] = 10'h000;
    ram[599] = 10'h000;
    ram[600] = 10'h000;
    ram[601] = 10'h000;
    ram[602] = 10'h000;
    ram[603] = 10'h000;
    ram[604] = 10'h000;
    ram[605] = 10'h000;
    ram[606] = 10'h000;
    ram[607] = 10'h000;
    ram[608] = 10'h000;
    ram[609] = 10'h000;
    ram[610] = 10'h000;
    ram[611] = 10'h000;
    ram[612] = 10'h000;
    ram[613] = 10'h000;
    ram[614] = 10'h000;
    ram[615] = 10'h000;
    ram[616] = 10'h000;
    ram[617] = 10'h000;
    ram[618] = 10'h000;
    ram[619] = 10'h000;
    ram[620] = 10'h000;
    ram[621] = 10'h000;
    ram[622] = 10'h000;
    ram[623] = 10'h000;
    ram[624] = 10'h000;
    ram[625] = 10'h000;
    ram[626] = 10'h000;
    ram[627] = 10'h000;
    ram[628] = 10'h000;
    ram[629] = 10'h000;
    ram[630] = 10'h000;
    ram[631] = 10'h000;
    ram[632] = 10'h000;
    ram[633] = 10'h000;
    ram[634] = 10'h000;
    ram[635] = 10'h000;
    ram[636] = 10'h000;
    ram[637] = 10'h000;
    ram[638] = 10'h000;
    ram[639] = 10'h000;
  end
  always @(posedge clk) begin
    if (w_en)
      ram[w_addr] <= \$5 [9:0];
  end
  reg [9:0] _0_;
  always @(posedge clk) begin
    if (rd__en) begin
      _0_ <= ram[rd__addr];
    end
  end
  assign rd__data = _0_;
  assign \$2  = sample_clk + (* src = "/home/yym/workspace/fpga/RAM.py:35" *) 1'h1;
  assign \$3  = w_addr == (* src = "/home/yym/workspace/fpga/RAM.py:49" *) 10'h27f;
  assign \$4  = w_addr + (* src = "/home/yym/workspace/fpga/RAM.py:52" *) 1'h1;
  (* src = "/home/yym/workspace/fpga/RAM.py:30" *)
  always @(posedge clk)
    sample_clk <= \$6 ;
  (* src = "/home/yym/workspace/fpga/RAM.py:10" *)
  always @(posedge clk)
    w_en <= \$7 ;
  (* src = "/home/yym/workspace/fpga/RAM.py:16" *)
  always @(posedge clk)
    w_addr <= \$8 ;
  assign \$1  = sample_clk == (* src = "/home/yym/workspace/fpga/RAM.py:31" *) 17'h1869f;
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$1 ) begin
      \$6  = 17'h00000;
    end else begin
      \$6  = \$2 [16:0];
    end
    if (rst) begin
      \$6  = 17'h00000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$1 ) begin
      \$7  = 1'h1;
    end else begin
      \$7  = 1'h0;
    end
    if (rst) begin
      \$7  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$8  = w_addr;
    if (w_en) begin
      (* full_case = 32'd1 *)
      if (\$3 ) begin
        \$8  = 10'h000;
      end else begin
        \$8  = \$4 [9:0];
      end
    end
    if (rst) begin
      \$8  = 10'h000;
    end
  end
  assign wr__en = w_en;
  assign wr__addr = w_addr;
  assign wr__data = \$5 [9:0];
  assign visible = rd__en;
  assign x = rd__addr;
  assign r_data = rd__data[8:0];
  assign \$5  = { 3'h0, adc_value[11:3] };
endmodule

(* src = "/home/yym/workspace/fpga/VGATiming.py:38" *)
(* generator = "Amaranth" *)
module \top.timing (pix_clk, visible, hsync, vsync, h_cnt, v_cnt, pix_rst);
  reg \$auto$verilog_backend.cc:2355:dump_module$2  = 0;
  wire \$1 ;
  wire \$10 ;
  wire \$11 ;
  wire \$12 ;
  reg [9:0] \$13 ;
  reg [9:0] \$14 ;
  wire \$2 ;
  wire [10:0] \$3 ;
  wire [10:0] \$4 ;
  wire \$5 ;
  wire \$6 ;
  wire \$7 ;
  wire \$8 ;
  wire \$9 ;
  (* src = "/home/yym/workspace/fpga/VGATiming.py:34" *)
  output [9:0] h_cnt;
  reg [9:0] h_cnt = 10'h000;
  (* src = "/home/yym/workspace/fpga/./main.py:9" *)
  output hsync;
  wire hsync;
  (* src = "/home/yym/workspace/fpga/./main.py:35" *)
  input pix_clk;
  wire pix_clk;
  (* src = "/home/yym/workspace/fpga/./main.py:35" *)
  input pix_rst;
  wire pix_rst;
  (* src = "/home/yym/workspace/fpga/VGATiming.py:35" *)
  output [9:0] v_cnt;
  reg [9:0] v_cnt = 10'h000;
  (* src = "/home/yym/workspace/fpga/./main.py:9" *)
  wire vga_hsync;
  (* src = "/home/yym/workspace/fpga/./main.py:10" *)
  wire vga_vsync;
  (* src = "/home/yym/workspace/fpga/VGATiming.py:32" *)
  output visible;
  wire visible;
  (* src = "/home/yym/workspace/fpga/./main.py:10" *)
  output vsync;
  wire vsync;
  (* init = 10'h000 *)
  (* src = "/home/yym/workspace/fpga/VGATiming.py:34" *)
  wire [9:0] x;
  (* init = 10'h000 *)
  (* src = "/home/yym/workspace/fpga/VGATiming.py:35" *)
  wire [9:0] y;
  assign \$1  = h_cnt == (* src = "/home/yym/workspace/fpga/VGATiming.py:47" *) 10'h31f;
  assign \$2  = v_cnt == (* src = "/home/yym/workspace/fpga/VGATiming.py:50" *) 10'h20c;
  assign \$3  = v_cnt + (* src = "/home/yym/workspace/fpga/VGATiming.py:53" *) 1'h1;
  assign \$4  = h_cnt + (* src = "/home/yym/workspace/fpga/VGATiming.py:56" *) 1'h1;
  assign \$5  = h_cnt < (* src = "/home/yym/workspace/fpga/VGATiming.py:63" *) 10'h280;
  assign \$6  = v_cnt < (* src = "/home/yym/workspace/fpga/VGATiming.py:64" *) 9'h1e0;
  assign visible = \$5  & (* src = "/home/yym/workspace/fpga/VGATiming.py:63" *) \$6 ;
  assign \$7  = h_cnt >= (* src = "/home/yym/workspace/fpga/VGATiming.py:76" *) 10'h290;
  assign \$8  = h_cnt < (* src = "/home/yym/workspace/fpga/VGATiming.py:76" *) 10'h2f0;
  assign \$9  = \$7  & (* src = "/home/yym/workspace/fpga/VGATiming.py:76" *) \$8 ;
  assign hsync = ~ (* src = "/home/yym/workspace/fpga/VGATiming.py:76" *) \$9 ;
  assign \$10  = v_cnt >= (* src = "/home/yym/workspace/fpga/VGATiming.py:77" *) 9'h1ea;
  assign \$11  = v_cnt < (* src = "/home/yym/workspace/fpga/VGATiming.py:77" *) 9'h1ec;
  assign \$12  = \$10  & (* src = "/home/yym/workspace/fpga/VGATiming.py:77" *) \$11 ;
  assign vsync = ~ (* src = "/home/yym/workspace/fpga/VGATiming.py:77" *) \$12 ;
  (* src = "/home/yym/workspace/fpga/VGATiming.py:43" *)
  always @(posedge pix_clk)
    h_cnt <= \$13 ;
  (* src = "/home/yym/workspace/fpga/VGATiming.py:44" *)
  always @(posedge pix_clk)
    v_cnt <= \$14 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    (* full_case = 32'd1 *)
    if (\$1 ) begin
      \$13  = 10'h000;
    end else begin
      \$13  = \$4 [9:0];
    end
    if (pix_rst) begin
      \$13  = 10'h000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$14  = v_cnt;
    if (\$1 ) begin
      (* full_case = 32'd1 *)
      if (\$2 ) begin
        \$14  = 10'h000;
      end else begin
        \$14  = \$3 [9:0];
      end
    end
    if (pix_rst) begin
      \$14  = 10'h000;
    end
  end
  assign x = h_cnt;
  assign y = v_cnt;
  assign vga_hsync = hsync;
  assign vga_vsync = vsync;
endmodule

(* src = "/home/yym/workspace/fpga/VGADisplay.py:14" *)
(* generator = "Amaranth" *)
module \top.vga_display (r_data, x, y, w_addr, r, g, b, visible);
  reg \$auto$verilog_backend.cc:2355:dump_module$3  = 0;
  wire \$1 ;
  wire \$2 ;
  wire \$3 ;
  wire \$4 ;
  (* src = "/home/yym/workspace/fpga/./main.py:14" *)
  output [3:0] b;
  reg [3:0] b;
  (* src = "/home/yym/workspace/fpga/./main.py:13" *)
  output [3:0] g;
  reg [3:0] g;
  (* src = "/home/yym/workspace/fpga/VGADisplay.py:19" *)
  wire grid;
  (* src = "/home/yym/workspace/fpga/./main.py:12" *)
  output [3:0] r;
  reg [3:0] r;
  (* src = "/home/yym/workspace/fpga/RAM.py:14" *)
  input [8:0] r_data;
  wire [8:0] r_data;
  (* src = "/home/yym/workspace/fpga/./main.py:14" *)
  wire [3:0] vga_b;
  (* src = "/home/yym/workspace/fpga/./main.py:13" *)
  wire [3:0] vga_g;
  (* src = "/home/yym/workspace/fpga/./main.py:12" *)
  wire [3:0] vga_r;
  (* src = "/home/yym/workspace/fpga/VGATiming.py:32" *)
  input visible;
  wire visible;
  (* src = "/home/yym/workspace/fpga/RAM.py:16" *)
  input [9:0] w_addr;
  wire [9:0] w_addr;
  (* src = "/home/yym/workspace/fpga/VGATiming.py:34" *)
  input [9:0] x;
  wire [9:0] x;
  (* src = "/home/yym/workspace/fpga/VGATiming.py:35" *)
  input [9:0] y;
  wire [9:0] y;
  assign \$1  = ! (* src = "/home/yym/workspace/fpga/VGADisplay.py:21" *) x[5:0];
  assign \$2  = ! (* src = "/home/yym/workspace/fpga/VGADisplay.py:21" *) y[5:0];
  assign grid = \$1  | (* src = "/home/yym/workspace/fpga/VGADisplay.py:21" *) \$2 ;
  assign \$3  = x == (* src = "/home/yym/workspace/fpga/VGADisplay.py:31" *) w_addr;
  assign \$4  = y == (* src = "/home/yym/workspace/fpga/VGADisplay.py:43" *) r_data;
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    r = 4'h0;
    if (visible) begin
      if (\$3 ) begin
        r = 4'h0;
      end else if (grid) begin
        r = 4'hf;
      end else if (\$4 ) begin
        r = 4'hf;
      end
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    g = 4'h0;
    if (visible) begin
      if (\$3 ) begin
        g = 4'hf;
      end else if (grid) begin
        g = 4'hf;
      end else if (\$4 ) begin
        g = 4'hf;
      end
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    b = 4'h0;
    if (visible) begin
      if (\$3 ) begin
        b = 4'h0;
      end else if (grid) begin
        b = 4'hf;
      end else if (\$4 ) begin
        b = 4'h0;
      end
    end
  end
  assign vga_r = r;
  assign vga_g = g;
  assign vga_b = b;
endmodule

(* src = "/home/yym/workspace/fpga/XADCModule.py:13" *)
(* generator = "Amaranth" *)
module \top.xadc (vauxp1, vauxn1, rst, adc_value, clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$4  = 0;
  wire \$1 ;
  reg [11:0] \$2 ;
  reg \$3 ;
  (* src = "/home/yym/workspace/fpga/XADCModule.py:10" *)
  reg adc_ready = 1'h0;
  (* src = "/home/yym/workspace/fpga/XADCModule.py:9" *)
  output [11:0] adc_value;
  reg [11:0] adc_value = 12'h000;
  (* src = "/home/yym/workspace/fpga/./main.py:16" *)
  input clk;
  wire clk;
  (* src = "/home/yym/workspace/fpga/./main.py:16" *)
  wire \clk$6 ;
  (* src = "/home/yym/workspace/fpga/XADCModule.py:16" *)
  wire drdy;
  (* src = "/home/yym/workspace/fpga/./main.py:41" *)
  input rst;
  wire rst;
  (* src = "/home/yym/workspace/fpga/./main.py:19" *)
  input vauxn1;
  wire vauxn1;
  (* src = "/home/yym/workspace/fpga/./main.py:18" *)
  input vauxp1;
  wire vauxp1;
  (* src = "/home/yym/workspace/fpga/XADCModule.py:15" *)
  wire [15:0] xadc_data;
  (* src = "/home/yym/workspace/fpga/XADCModule.py:9" *)
  always @(posedge clk)
    adc_value <= \$2 ;
  (* src = "/home/yym/workspace/fpga/XADCModule.py:10" *)
  always @(posedge clk)
    adc_ready <= \$3 ;
  (* src = "/home/yym/workspace/fpga/XADCModule.py:19" *)
  xadc_wiz_0 u_xadc (
    .daddr_in(7'h11),
    .dclk_in(clk),
    .den_in(\$1 ),
    .di_in(16'h0000),
    .do_out(xadc_data),
    .drdy_out(drdy),
    .dwe_in(1'h0),
    .eoc_out(\$1 ),
    .reset_in(1'h0),
    .vauxn1(vauxn1),
    .vauxp1(vauxp1),
    .vn_in(1'h0),
    .vp_in(1'h0)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$4 ) begin end
    \$2  = adc_value;
    if (drdy) begin
      \$2  = xadc_data[15:4];
    end
    if (rst) begin
      \$2  = 12'h000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$4 ) begin end
    (* full_case = 32'd1 *)
    if (drdy) begin
      \$3  = 1'h1;
    end else begin
      \$3  = 1'h0;
    end
    if (rst) begin
      \$3  = 1'h0;
    end
  end
  assign \clk$6  = clk;
endmodule
